### ISSUE TITLE
Ancillary windows disappear across multiple monitors

### ISSUE THREAD

**Issue by meganhenriksen** [DOI-USGS/ISIS3#3468] opened 2019-10-08 19:03 UTC
**ISIS version(s) affected**: at least 3.6 and above

**Description**  
When using x11 forwarding from Ubuntu to OSX ancillary windows such as the Control Network Navigator in qnet or the Advanced Stretch Tool in qview will disappear when moved from one monitor to another.  The window continues to exist (if you show everything in the workspace), but there isn't a simple way of retrieving it from off-screen. 

This especially happens if the extra monitor is placed on the left side of the Mac (a common set up, since all the usb ports are on the right). Digging into it, it appears to be related to the QT library.

**How to reproduce**  
Most of this is in the description, but:
1. Have a Mac with an extra monitor attached, set up on the left side of the mac.
2. Sign into an ubuntu system and use x11 forwarding
3. Open qview or qnet 
4. Move a window such as the control network navigator or the advanced stretch tool in qview to the other monitor. 

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment] 2019-11-20 00:04
I can confirm I was able to reproduce this on my Mac. On Mac OS 10.13, I ran qmos over X11 on an Ubuntu 18 system and when I moved the open file dialog from one monitor to another it disappeared. My main window was still locked indicating the sub window was still open.

**Comment by jessemapel** [comment] 2019-11-20 00:20
I was also able to confirm this was a problem in ISIS3.5.0

@meganhenriksen What are you using to do X11 on your mac? I was able to reproduce this with XQuartz.

**Comment by Kelvinrr** [comment] 2019-12-16 21:15
I was able to replicate this using non-ISIS apps. Specifically, the sub-window doesn't join the other monitor's desktop and instead stays within same desktop but out of view. This seems to be an XQuartz issue. I will spend some time to see if I can find a workaround. Can you answer Jesse's question about what you are using for X11 on Mac?

**Comment by Kelvinrr** [comment] 2019-12-16 21:30
![destop_issue](https://user-images.githubusercontent.com/13245976/70944450-52446100-2010-11ea-80fd-69af9ff0736e.gif)

Example showing the problem. Note when I zoom out and the window is still in the same desktop but out of view (you just have to trust it disappeared as soon as I dropped it into the other desktop). And this happens with any app I use x11 forwarding on from Ubuntu to Mac, not just ISIS. 

If you can confirm the same on your side that would be great.

**Comment by gravatite** [comment] 2019-12-16 21:36
> @meganhenriksen What are you using to do X11 on your mac? I was able to reproduce this with XQuartz.

We are also using XQuartz at LROC.

**Comment by Kelvinrr** [comment] 2019-12-16 22:01
XQuartz issue currently open: https://gitlab.freedesktop.org/xorg/xserver/issues/764

A workaround that I tested and worked: https://discussions.apple.com/thread/5477021

That workaround requires a reset on your Mac box and would put you in a legacy mode that is less than ideal if you really like your multi-desktop setup in MacOS. But it seems like an issue Apple and Xquartz need to sort out and seems out of scope for us.

**Comment by Kelvinrr** [comment] 2019-12-18 01:51
Closing. If anything changes we can re-open.

**Closed as completed by Kelvinrr** 2019-12-18 01:51 UTC
Labels: bug, Missions
