### ISSUE TITLE
spiceinit failed for OSIRIS-REx OCAMS .cub images

### ISSUE THREAD

**Issue by gengxun-rs** [DOI-USGS/ISIS3#4177] opened 2020-12-08 08:32 UTC
When I used spiceinit to initialize the .cub images derived from OSIRIS-REx OCAMS raw data, it reported errors as follows:

Group = Kernels
  NaifFrameCode             = -64360
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                               $osirisrex/kernels/pck/bennu_v15.tpc,
                               $osirisrex/kernels/FK/orx_v14.tf)
  TargetPosition            = $base/kernels/spk/de430.bsp
  InstrumentPointing        = (/home/gx/anaconda3/envs/isis/data/osirisr-
                               ex/kernels/ck/orx_ola_190404_scil2id03008.bc,
                               $osirisrex/kernels/fk/orx_v14.tf,
                               $osirisrex/kernels/fk/orx_shape_v01.tf)
  Instrument                = $osirisrex/kernels/ik/orx_ocams_v07.ti
  SpacecraftClock           = $osirisrex/kernels/sclk/orx_sclkscet_00059.tsc
  InstrumentPosition        = /home/gx/anaconda3/envs/isis/data/osirisre-
                              x/kernels/spk/orx_190401_190522_190508_od137_v1-
                              .bsp
  InstrumentAddendum        = Null
  ShapeModel                = Null
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 1
  Error                     = "Can not find [INS-64360_TRANSX] in text
                               kernels"
End_Group
**ERROR** Unable to initialize camera model.

However, the   InstrumentAddendum  (IAK) related files are not provided in the OSIRIS-REx kernel files. 
Please help me to fix this problem.

Thanks a lot.

**Comment by jessemapel** [comment] 2020-12-08 14:13
Hi, this is a duplicate of #4060. We're looking into adding the ORex kernels which should resolve this problem.

**Closed as completed by jessemapel** 2020-12-08 14:13 UTC
