### ISSUE TITLE
APM crashes or returns bogus data for LROC

### ISSUE THREAD

**Issue by gcushing** [DOI-USGS/ISIS3#3169] opened 2019-03-15 23:54 UTC
This SOCET issue is affecting our ability to convert a SOCET control network to ISIS3.

**Description**
APM in SOCET either crashes or returns bad points. Bad points appear to result from some of the input images being improperly rotated. Additionally, sometimes images will display incorrectly but somehow correct themselves when the zoom function is used.

**How to reproduce**
Open SOCET project Aitken_Basin_np1 (Sallah workstation).

Files are located on Sallah - D:DATA/Aitken_Basin_np1

In SOCET, open MST. 

Bad points can be examined using IPM, or they can be recreated using APM.

Additional context is forthcoming.

**Comment by jlaura** [comment] 2019-03-16 02:23
We are going to need significantly more information on this before we can begin to assess. 

The dev team is not familiar with SOCET, so a step-by-step with a clearly identified point where the results are not as expected is going to be needed. 

Additionally, we are only able to access the code for the sensor model, so it may be more valuable to attempt to externally validate the sensor. We can not access the SOCET source, so if the error is inside of SOCET, we can not address it.

To move forwards, can you please (1) identify where the team suspects the issue is, (2) provide a sep-by-step workflow that can be reproduced by a non-socet user, and (3) suggest whether this issue is inside of the code we have access to or SOCET (I know that this last one is probably not realistic, but any starting point would be beneficial).

Thanks!

**Comment by jlaura** [comment] 2019-05-14 14:12
@gcushing @blandoplanet I am going to close this issue for now. Please reopen when additional information is available and we can reproduce.

**Closed as completed by jlaura** 2019-05-14 14:12 UTC
