### ISSUE TITLE
Builds Failing From Missing Unittest file

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ISIS3#5461] opened 2024-04-13 00:29 UTC
**ISIS version(s) affected**: dev

**Description**  
From PR #5427 there was/is a missing unittest.cpp file that caused weird build errors and failing tests on linux. @kledmundson It seems like this was not caught and I am unsure why.

**How to reproduce**  
Try to build and run unittests on linux systems from a clean slate.

**Possible Solution**  
Can the missing file be added @kledmundson 

**Additional context**

**Comment by kledmundson** [comment] 2024-04-13 00:44
looking at it

**Comment by kledmundson** [comment] 2024-04-13 01:02
Wondering if the problem is not the missing unit test but that I accidentally left in the file _IrregularBodyCameraGroundMap.truth_ in the IrregularBodyCameraGroundMap directory? What do you think? I can regenerate the unit test or remove the truth data file.

**Comment by AustinSanders** [comment] 2024-04-14 22:45
Closed by #5462

**Closed as completed by AustinSanders** 2024-04-14 22:45 UTC
Labels: bug
