### ISSUE TITLE
Cannot install anaconda on Mac Mini with M2 chip

### ISSUE THREAD

**Issue by cneish** [DOI-USGS/ISIS3#5164] opened 2023-03-30 13:45 UTC
**ISIS version(s) affected**: All

**Description**  
I just purchased a new Mac Mini (2023) with an M2 chip installed. When I try to install anaconda, it says "This package is incompatible with this version of macOS. The package is trying to install content to the system volume. Contact the software manufacturer for assistance." I got the same error message for both the "regular" Mac install and the "M1" Mac install.

Do you know of a way around this? Alternatively, is there a way to install ISIS without using anaconda?

Thanks, Catherine

**Comment by rbeyer** [comment] 2023-03-30 14:35
How exactly are you trying to install Anaconda on your M1/M2 Mac?  If you are following the ISIS install instructions for either Anaconda or Miniconda does the file you have downloaded have "arm64" in its name (no matter if it ends with .sh or .pkg)?  If it has "x86_64" in its filename then you have the wrong installer file (that's for the older Intel Macs).

**Comment by rbeyer** [comment] 2023-03-30 14:38
There's also some discussion about ISIS on Apple Silicon (M1/M2 chips) in #4753, but it does not seem to have closed.  I don't yet have an Apple Silicon Mac, so my advice is limited, but it seems like you should at least be able to get conda installed.  Whether ISIS will then work is a separate issue.

**Comment by cneish** [comment] 2023-03-30 15:05
I downloaded the .pkg file, and clicked on it. I got the same error message for the "arm64" and the "x86_64" files.

Weirdly, I was able to install ISIS on my M1 Mac laptop. I'm thinking it might be an issue with the operating system (masOS v12 vs. v13)?

**Comment by AustinSanders** [comment] 2023-03-30 16:25
@cneish I don't have access to an M2 mac, but based on https://community.anaconda.cloud/t/mac-m2-ventura-support-2023-03-anaconda-miniconda/52526 , there appears to be an issue with the .pkg installer on m2 mac that is not present with the shell installer.

I have no way of verifying that this will solve the issue, but it may be worth trying the .sh installer.

**Comment by cneish** [comment] 2023-03-30 16:37
Thanks. I will try that out and report back.

**Comment by cneish** [comment] 2023-03-30 19:03
That worked! I was able to install anaconda. However, I'm now running into trouble installing ISIS. It claims the package is not found on the current channels (see output below):


(isis) Catherines-Mac-mini:~ cneish$ conda install -c usgs-astrogeology isis=7.0.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - isis=7.0.0

Current channels:

  - https://conda.anaconda.org/usgs-astrogeology/osx-arm64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by AustinSanders** [comment] 2023-03-30 21:29
@cneish I was able to replicate that error when using conda, but everything solves correctly when I use mamba. In your isis environment, try:
``` 
conda install mamba
mamba install -c usgs-astrogeology isis=7.0.0
```

In general, mamba seems to resolve dependencies significantly faster than conda, and it'll occasionally resolve dependencies / install packages that conda can't seem to figure out.

**Comment by cneish** [comment] 2023-03-30 22:30
@AustinSanders I installed mamba, but I couldn't use it to install ISIS. It seems like there aren't any files in the usgs-astrogeology channel?

(isis) Catherines-Mac-mini:~ cneish$ mamba install -c usgs-astrogeology isis=7.0.0      

Looking for: ['isis=7.0.0']                                                               
                                                                                          
usgs-astrogeology/osx-arm64                        136.0 B @ 546.0 B/s  0.2s
usgs-astrogeology/noarch                           130.0 B @ 496.0 B/s  0.3s
pkgs/r/osx-arm64                                   118.0 B @ 303.0 B/s  0.1s
pkgs/main/osx-arm64                                  1.4MB @   2.6MB/s  0.6s
pkgs/main/noarch                                   820.3kB @   1.4MB/s  0.4s
pkgs/r/noarch                                        1.3MB @   1.8MB/s  0.4s
conda-forge/osx-arm64                                5.7MB @   2.8MB/s  2.2s
conda-forge/noarch                                  11.7MB @   3.2MB/s  3.9s

Pinned packages:                                                                          
  - python 3.11.*                                                                         
                                                                                          
                                                                                          
Could not solve for environment specs                                                     
The following package could not be installed                                              
└─ isis 7.0.0**  does not exist (perhaps a typo or a missing channel).

**Comment by AustinSanders** [comment] 2023-03-30 23:00
@cneish This is basically issue #4753 .  I was hoping that it would at least *attempt* to install so that we could try to troubleshoot.  It looks like, because you are on an M2 mac, mamba is searching for a specific osx-arm64 package, and the supported version of isis is located in osx-64 instead.

ISIS cannot be officially supported on M1/M2 until the development team has access to mac ARM machines, as we have no way to compile, test, and publish to anaconda forge.

Regarding "Alternatively, is there a way to install ISIS without using anaconda?" you may be able to compile ISIS from source as described in the [developer reference guide](https://github.com/DOI-USGS/ISIS3/wiki/Developing-ISIS3-with-cmake).  It's a fairly hands-on process, but I can do my best to help.  I'm not sure if there will be issues specifically related to the ARM architecture.  If there are any ARM-specific issues, then I will likely not be able to provide much help.

**Comment by cneish** [comment] 2023-03-30 23:58
@AustinSanders I do find it odd that I successfully installed ISIS on my M1 Mac laptop last year. Are the M1 and M2 chips that different?

This is really unfortunate, as I bought this machine with the main intent for it to run ISIS. I may try to install the legacy version of ISIS, if it is still available.

**Comment by cneish** [comment] 2023-03-31 00:04
Never mind, the legacy version doesn't work either. I will have to wait until my husband has time to help me compile ISIS from source.

In the meantime, I don't suppose I could ship you a Mac ARM machine for testing? (Only half joking...)

**Comment by AustinSanders** [comment] 2023-03-31 05:57
I feel kind of silly suggesting this, but if you got isis installed on an M1 mac via conda previously, then it may be worth a shot?

You can specify the release platform as part of the conda install command as discussed [here](https://stackoverflow.com/questions/55288315/specify-platform-during-package-install), but I'm not sure what the expected behavior is when forcing an install meant for a different platform.  I suspect that the packages will install, but that they will not be usable.

``` mamba install -c usgs-astrogeology/osx-64 isis ```

**Comment by cneish** [comment] 2023-03-31 12:46
@AustinSanders The output here is more promising, but there's no installation target for "ale". Do you know what channel "ale" might be in?

`Looking for: ['isis']

usgs-astrogeology/noarch                                      No change
usgs-astrogeology/osx-arm64                                   No change
usgs-astrogeology/osx-64                            20.4kB @  33.4kB/s  0.6s
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
pkgs/r/osx-arm64                                              No change
pkgs/main/osx-arm64                                  1.4MB @   1.3MB/s  0.5s
conda-forge/osx-arm64                                5.7MB @   3.2MB/s  1.9s
conda-forge/noarch                                  11.7MB @   3.2MB/s  3.9s

Pinned packages:
  - python 3.11.*


Could not solve for environment specs
The following packages are incompatible
└─ isis   is uninstallable because there are no viable options
   ├─ isis [3.10.0|3.10.1|3.10.2] would require
   │  └─ armadillo 8.200.0 , which does not exist (perhaps a missing channel);
   ├─ isis 4.1.0 would require
   │  └─ ale <0.8 , which does not exist (perhaps a missing channel);
   ├─ isis 4.4.0 would require
   │  └─ ale >=0.8.5 , which does not exist (perhaps a missing channel);
   ├─ isis 7.2.0 would require
   │  └─ ale >=0.8.6,<0.8.7.0a0 , which does not exist (perhaps a missing channel);
   ├─ isis [7.0.0|7.1.0] would require
   │  └─ ale >=0.8.6,<1.0a0 , which does not exist (perhaps a missing channel);
   ├─ isis [5.0.0|5.0.1|5.0.2|6.0.0] would require
   │  └─ ale >=0.8.5,<1.0a0 , which does not exist (perhaps a missing channel);
   ├─ isis 4.0.0 would require
   │  └─ ale 0.7.1 , which does not exist (perhaps a missing channel);
   ├─ isis [4.1.1|4.2.0] would require
   │  └─ ale >=0.8.1 , which does not exist (perhaps a missing channel);
   ├─ isis 4.0.1 would require
   │  └─ ale >=0.7.1 , which does not exist (perhaps a missing channel);
   └─ isis 4.3.0 would require
      └─ ale >=0.8.4 , which does not exist (perhaps a missing channel).
`

**Comment by AustinSanders** [comment] 2023-03-31 16:18
I think you'll have to specify all the usgs-astrogeology packages in the install command so that they target the alternate platform.  To the best of my knowledge, none of USGS ASC's packages are currently supported on Mac ARM, so they'll be in the osx-64 directory.

The conda installation on an ARM Mac is likely going to be a dead end at the moment.   We can work through each of these individual installation issues and will likely arrive at the fact that the architecture is fundamentally different and will not work correctly even if installed.

Our best bet here is to compile from source, but I'm also happy to continue experimenting with the conda side of things if you'd find that useful.

**Comment by cneish** [comment] 2023-03-31 16:32
ARM Macs have been on the market for almost two years, and all new Macs are ARM. What is the current timeline for supporting ARM Macs? Or is ISIS planning to drop Mac as a supported platform? Thanks.

**Comment by AustinSanders** [comment] 2023-03-31 17:11
Unfortunately, I don't have a great answer for that.  We don't currently have an established timeline for supporting ARM Macs, but we also do not plan to drop Mac as a supported platform.  As issues like this continue to pop up, it pushes support for ARM Mac further up in our list of priorities.

I brought this issue up during our daily software meeting, and the issue of supporting ARM Mac is very much on our radar.  Unfortunately, until the ASC software team has access to ARM Mac hardware, we must rely on the open source community / external contributors who have access to ARM architecture to support this effort, and we have yet to see any external contributors take ownership of this task.

Since the topic of this issue has changed to a discussion of ARM Macs, I am closing this issue.  Further discussion should take place on issue #4753

**Closed as completed by AustinSanders** 2023-03-31 17:11 UTC
Labels: bug

**Comment by cneish** [comment] 2023-03-31 17:24
FYI, my husband found a work-around for installing ISIS on my Mac using an emulator. He is updating the installation instructions on GitHub, which I hope you will post for other users who find themselves in this situation. Thanks.

**Comment by AustinSanders** [comment] 2023-03-31 17:28
That's excellent!  I look forward to seeing how it works, and we appreciate your effort.
