### ISSUE TITLE
ISIS3 Installs Incorrect Version of OpenCV

### ISSUE THREAD

**Issue by astrostu** [DOI-USGS/ISIS3#4013] opened 2020-09-11 03:01 UTC
**ISIS version(s) affected**: 3.x (tested on 3.9.1, 3.10.0, 3.10.2)

**Description**  
The OpenCV library that is installed with ISIS3 (possibly 4?) on Linux variants is not the correct version.  It says it installs v 3.4.1.  But, when I run `sudo find / -name "libopencv_core.so*"`, nothing is found.  When I try to run any ISIS3 programs (such as qnet, or findimageoverlaps, or cnetedit), this error is returned: `error while loading shared libraries: libopencv_calib3d.so.3.2: cannot open shared object file: No such file or directory`

**How to reproduce**  
I created a new virtual machine running Kubuntu v20, ran into this problem, and then went back to a different new virtual machine, Ubuntu v18.  It was a clean install of the OS.  I followed the instructions for installing ISIS v3 (a side-note is that v4 would not install, it was just not findable), but after installing, no ISIS3 application would run.  I consistently got the error, `error while loading shared libraries: libopencv_calib3d.so.3.2: cannot open shared object file: No such file or directory`.  Running `ldd $ISISROOT/bin/[ISIS program, such as cnetedit]`, I got (truncated):

```
	linux-vdso.so.1 (0x00007ffe891c7000)
	...
	libopencv_calib3d.so.3.2 => not found
	libopencv_core.so.3.2 => not found
	libopencv_features2d.so.3.2 => not found
	libopencv_flann.so.3.2 => not found
	libopencv_imgcodecs.so.3.2 => not found
	libopencv_imgproc.so.3.2 => not found
	libopencv_xfeatures2d.so.3.2 => not found
	...
```

**Possible Solution**  
After a full 11 hours of G**gling, on the Ubuntu install, this finally worked:  `conda install -c conda-forge opencv=3.2`.  After running that, I re-ran the ISIS install, and then tried an ISIS program, and the GUI appeared.  I then went back to my Kubuntu VM and the same process worked.

**Additional context**  
My code now appears to be running (still testing but it at least started this time), so it really looks like this is a "simple" versioning issue.  I would note again that these were clean, minimal installs of Linux that I tried on, so it's possible that normal people who often use Linux already have this installed so it's no issue for them.  I would also note that my searching shows that OpenCV is well into version 4, so you might want to update the dependency, if possible?

**Comment by jessemapel** [comment] 2020-09-11 16:34
This is a known issue for old releases, but it should be fixed in 3.10.2. Here's the linux deps for 3.10.2:

<details>
  <summary>Ubuntu 18 conda search</summary>

```

conda search -c usgs-astrogeology isis=3.10.2 -i
Loading channels: done
isis 3.10.2 py36_0
------------------
file name   : isis-3.10.2-py36_0.tar.bz2
name        : isis
version     : 3.10.2
build       : py36_0
build number: 0
size        : 13.6 MB
subdir      : linux-64
url         : https://conda.anaconda.org/usgs-astrogeology/linux-64/isis-3.10.2-py36_0.tar.bz2
md5         : e63fec91611e11331b6c746d6c90a1d2
timestamp   : 2020-05-08 06:28:56 UTC
dependencies: 
  - armadillo 8.200.0
  - blas 1.1
  - boost 1.67
  - bullet 2.86.1
  - bz2file 0.98
  - bzip2 1.0.6
  - cspice 66
  - curl 7.60.0
  - eigen 3.3.3
  - embree 2.14.0
  - geos 3.5.1
  - geotiff 1.4.2
  - gmm 5.0
  - gmp 6.1.2
  - gsl 2.2.1
  - hdf5 1.8.18
  - icu 58.2
  - jama 125
  - jpeg 9b
  - kakadu 1
  - krb5 1.14.2
  - libpng >=1.6.34
  - libprotobuf 3.5.2
  - libtiff >=4.0.9
  - libxml2 2.9.7
  - mesalib 17.2.0
  - mysql 5.7.20
  - mysql-connector-c 6.1.6
  - nanoflann 1.2.2
  - nn
  - openblas 0.2.19
  - opencv 3.2.0
  - openssl 1.0.2n
  - pcl 1.8.1
  - pip 9.0.1
  - protobuf 3.5.2
  - python 3.6
  - qhull ==7.2.0 0
  - qt 5.9.6.*
  - qwt 6.1.3.*
  - setuptools 38.5.1.*
  - sip 4.18
  - sqlite 3.13.0
  - suitesparse 4.5.4
  - superlu 5.2.1
  - tnt ==126 0
  - wheel 0.30.0
  - x264 20131218
  - xerces-c 3.1.4
  - xorg-kbproto 1.0.7
  - xorg-libice
  - xorg-libsm
  - xorg-libx11 1.6.4
  - xorg-libxi
  - zlib 1.2.11

```

</details>

And here's Mac 10.13:

<details>
  <summary>Mac 10.13 conda search</summary>

```

conda search -c usgs-astrogeology isis=3.10.2 -i
Loading channels: done
isis 3.10.2 py36_0
------------------
file name   : isis-3.10.2-py36_0.tar.bz2
name        : isis
version     : 3.10.2
build       : py36_0
build number: 0
size        : 12.6 MB
subdir      : osx-64
url         : https://conda.anaconda.org/usgs-astrogeology/osx-64/isis-3.10.2-py36_0.tar.bz2
md5         : f67edca2e1a205597573483cfa9b3c26
timestamp   : 2020-05-08 04:53:54 UTC
dependencies: 
  - armadillo 8.200.0
  - blas 1.1
  - boost 1.67
  - bullet 2.86.1
  - bz2file 0.98
  - bzip2 1.0.6
  - cspice 66
  - curl 7.60.0
  - eigen 3.3.3
  - embree 2.14.0
  - geos 3.5.1
  - geotiff 1.4.2
  - gmm 5.0
  - gmp 6.1.2
  - gsl 2.2.1
  - hdf5 1.8.18
  - icu 58.2
  - jama 125
  - jpeg 9b
  - kakadu 1
  - krb5 1.14.2
  - libpng >=1.6.34
  - libprotobuf 3.5.2
  - libtiff >=4.0.9
  - libxml2 2.9.7
  - mesalib 17.2.0
  - mysql 5.7.20
  - mysql-connector-c 6.1.6
  - nanoflann 1.2.2
  - nn
  - openblas 0.2.19
  - opencv 3.2.0
  - openssl 1.0.2n
  - pcl 1.8.1
  - pip 9.0.1
  - protobuf 3.5.2
  - python 3.6
  - qhull ==7.2.0 0
  - qt 5.9.6.*
  - qwt 6.1.3.*
  - setuptools 38.5.1.*
  - sip 4.18
  - sqlite 3.13.0
  - suitesparse 4.5.4
  - superlu 5.2.1
  - tnt ==126 0
  - wheel 0.30.0
  - x264 20131218
  - xerces-c 3.1.4
  - xorg-kbproto 1.0.7
  - xorg-libice
  - xorg-libsm
  - xorg-libx11 1.6.4
  - xorg-libxi
  - zlib 1.2.11

```

</details>

Updating to OpenCV 4 is problematic for findfeatures. Many of the algorithms that it uses were removed from opencv around 3.4 or 3.5.

I am testing this on Ubuntu18 right now to see if I can reproduce.

**Comment by astrostu** [comment] 2020-09-11 16:42
I did "conda install -c usgs-astrogeology isis3" first because that's what I had written down in my own install guide from The Before Times, which installed the 3.9.x version of ISIS and I had the OpenCV errors.  I know I then did "conda install -c usgs-astrogeology isis" which installed 3.10.0, not 3.10.2, not 4.x.  It still had OpenCV errors.  Then I searched around and finally got OpenCV v3.2 installed.  Then because it had a lot of its own dependencies, I did "conda install -c usgs-astrogeology isis" again to make sure it would not be broken, which installed version 3.10.2 of ISIS (not 3.10.0, not 4.x).

So, there's also something weird with what version of ISIS is being installed, because I don't think it should be doing 3.10.0 and then I have to install ISIS again to get 3.10.2.  Maybe it only did 3.10.2 once it saw that v3.2 of OpenCV was installed?  But that doesn't make sense.  Anyway, this weirdness happened both in Kubutu v20 and Ubuntu v18.

**Comment by jessemapel** [comment] 2020-09-11 18:50
@astrostu Can you try just installing 3.10.2 directly into a new environment? Installing the isis3 package and then the isis package can cause a lot of issues.

**Comment by astrostu** [comment] 2020-09-11 19:46
Okay, I'm not quite sure what's going on now.  I created a new conda environment ("isisTest"), and when I run `conda install -c usgs-astrogeology isis3` it wants to install opencv version 3.2 now, when before it was always installing 3.4.  Similarly, `conda install -c usgs-astrogeology isis` installs 3.2.  It also wants to install ISIS v 4.2, which it wouldn't do for me before.

To try to replicate this again, I'd need to install an entirely new virtual machine (again) which I'd rather not do, but will if you need me to to try to replicate it again.  Perhaps it is enough to close this issue and then if people encounter it in the future, they can find it through searching and find my solution, or your note that they should update their ISIS version?

That said, `conda install -c usgs-astrogeology isis3` still wants to install 3.9.1.  Explicitly stating isis3=3.10.0 does work for installing that version, while explicitly stating isis3=3.10.2 installs that one.  Is the first sentence in this paragraph expected behavior?

**Comment by jessemapel** [comment] 2020-09-14 14:58
The isis**3** package on anaconda cloud only has versions up to 3.9.1 which is why you are seeing that behavior. isis 3.10.0 and beyond are only served on the **isis** package on anaconda cloud. So, that is expected behavior. I'm also very concerned about you switching between the two packages. In Anaconda, they are considered _different_ packages and it will attempt to install them side by side.

In short, If you want to use 3.9.1 or earlier then you need to use the isis**3** package on Anaconda. If you want to use 3.10 or later then you need to use the isis package on Anaconda. You **should not** attempt to upgrade from 3.9.1 or earlier to 3.10 or later in the same environment.

I am going to close this issue as the packages are working correctly and we are not going to be re-doing the 3.9 build to get openCV 3.2 because there is a work-around documented here.

**Closed as completed by jessemapel** 2020-09-14 14:58 UTC
Labels: wontfix, installation
