### ISSUE TITLE
not a valid Kaguya Spectral Profiler file

### ISSUE THREAD

**Issue by whfarrand05** [DOI-USGS/ISIS3#3143] opened 2019-03-06 17:30 UTC
I asked about the kaguyasp2ascii routine a couple of years ago (or maybe it was then "kaguyasp2isis"). At any rate, I just reinstalled ISIS3 and tried to read in a file downloaded just today from darts.isas.jaxa.jp site and got the following error message:

**USER ERROR** Input file [SP_2C_03_04184_N187_E0053.spc] is not a valid Kaguya Spectral Profiler file.

Did the format of the files change to make them incompatible with "kaguyasp2ascii"?

**Comment by jlaura** [comment] 2019-03-06 18:52
@whfarrand05 Thanks for the report. If you are simply looking to get access to the data and then work with it in another application,  I would suggest looking at our plio library.  Specifically: https://gist.github.com/jlaura/bf2f9aef86f2a1b0a2199341b195c72b

The above feedback is an alternative solution. In the future, will you submit issues like this using our bug template?  The information requested in the template will help us directly address and investigate issues such as this in the future.

**Comment by whfarrand05** [comment] 2019-03-06 18:59
Thanks.  That works for that file, but how do I access other Spectral Profiler files?  I’ll endeavor to use that bug template in the future.

Bill

**Comment by jlaura** [comment] 2019-03-06 20:08
@whfarrand05 Can you open a question for us at https://astrodiscuss.usgs.gov? You can use your GitHub login and then we can get your question answered outside of the issue stream.  See you over there!

**Comment by whfarrand05** [comment] 2019-03-14 18:21
Hi,
  I tried sending a reply to you about an error running plio on the astrodiscuss.usgs.gov site forum, but apparently I can’t get it to post.. I keep getting a “404 Not Found” message on that site when I hit the reply button.

   The message I was trying to send via the forum is pasted below:

>>
I actually had Anaconda installed on my machine already; however, after changing to the directory with a SP file and entering the command from your example, I got the following error message

sp_spex1=plio.io.io_spectral_profiler.Spectral_Profiler('SP_2C_03_04184_N187_E0053.spc')
Traceback (most recent call last):

  File "<ipython-input-9-744061d29e53>", line 1, in <module>
    sp_spex1=plio.io.io_spectral_profiler.Spectral_Profiler('SP_2C_03_04184_N187_E0053.spc')

  File "C:\Users\whfar\Anaconda3\lib\site-packages\plio\io\io_spectral_profiler.py", line 53, in __init__
    label = pvl.load(input_data)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\__init__.py", line 96, in load
    return decoder.decode(fp)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 230, in decode
    module = PVLModule(self.parse_block(stream, self.has_end))

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 249, in parse_block
    statement = self.parse_statement(stream)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 304, in parse_statement
    return self.parse_assignment(stream)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 475, in parse_assignment
    self.ensure_assignment(stream)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 466, in ensure_assignment
    self.expect(stream, self.assignment_symbole)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 163, in expect
    self.raise_error(msg % (actual, expected), stream)

  File "C:\Users\whfar\Anaconda3\lib\site-packages\pvl\decoder.py", line 151, in raise_error
    raise ParseError(msg, stream.pos, stream.lineno, stream.colno)

ParseError: Unexpected token b')' (expected b'=')

>>>
So not sure what happened there...

**Comment by jlaura** [comment] 2019-03-14 18:25
@whfarrand05 Apologies for the 404 - happy to keep working on this over here. Weird error! It looks like the label is having issues (the error is from the PVL library not being able to parse something). Let me try that specific file to see what is going on there. I believe I can pull that file off the team's data downloader?

**Comment by whfarrand05** [comment] 2019-03-14 18:59
Thanks, that file was just one I downloaded from the JAXA web site.  Should be similar to any other recent vintage SP file I imagine.

Bill

**Comment by jlaura** [comment] 2019-03-14 19:22
One question: Is this the version 3.0 2C data that they are releasing? I am not sure when the V3-2C data started hitting the web. Thanks!

**Comment by whfarrand05** [comment] 2019-03-14 19:25
What it says on the JAXA DARTS site regarding the data product is:

Data set ID:        SLN-L-SP-4-LEVEL2C-V3.0
Data set name:  SELENE MOON SP 4 LEVEL2C V3.0

**Comment by jlaura** [comment] 2019-03-29 02:59
I was finally able to get back to looking at this. The data that this is reported on does not include a header. So the reader is hitting the binary and trying to parse out a label that is separate. I am going to open an issue both here and on the `plio` repositories to have these data be supported where the label is detached.

**Comment by jlaura** [comment] 2019-03-29 03:05
I just open #3196 as an enhancement request. I am going to close this issue as this is not a bug in the software, but a breakage due to how the data are being shipped. The enhancement should cover adding the ability to read the V3.0 2C spc files.

**Closed as completed by jlaura** 2019-03-29 03:05 UTC

**Comment by jlaura** [comment] 2019-03-29 03:55
@whfarrand05 I have a fix in as a pull request in plio. The testing is working locally, but I want to try this out on a few files as well. I wanted to alert you in case this was time sensitive and you wanted to test the change over there before we build and release a new version.

https://github.com/USGS-Astrogeology/plio/pull/105

I'll likely get that merged and released sometime next week. No ETA on the ISIS fix.

**Comment by whfarrand05** [comment] 2019-03-29 13:08
Well, it’s a little late now since I was thinking of talking about using the Spectral Profiler data in a Lunar Data Analysis Program proposal (submitting to NASA today), but once the fix is set I could use the data in the future.

Bill
