### ISSUE TITLE
ISIS 8.0.1 version is required to fix the downloadIsisData script

### ISSUE THREAD

**Issue by Hplanet** [DOI-USGS/ISIS3#5307] opened 2023-10-11 00:44 UTC
Description:

The latest version of ISIS 8.0.1 requires to fix downloadIsisData script as it doesn't fetch all required calibration files-->

Example: 
After installation of latest version of ISIS DATA and mission specific data, example LRO DATA, it doesn't fetch all calibration files unlike the older version of ISIS. Something is broken while using command 'downloadIsisData'. 
The File name I found missing is: NACR_linearizationCoefficient and many more with this name.

 Please resolve this.

**Comment by AustinSanders** [comment] 2023-10-11 17:56
Hi @Hplanet,

Please fill out the template in the bug report / feature request. We cannot provide any assistance until we have sufficient context for this issue.

**Comment by Hplanet** [comment] 2023-10-11 19:22
Hi @AustinSanders 
I already did that. added feature request. and described as here under. Sorry it was not appearing previously untill you click it.

Description:
The latest version of ISIS 8.0.1 requires to fix downloadIsisData script as it doesn't fetch all required calibration files

Example:
After installation of latest version of ISIS DATA and mission specific data, example LRO DATA, it doesn't fetch all calibration files unlike the older version of ISIS. Something is broken while using command 'downloadIsisData'. 
The File name I found missing is: NACR_linearizationCoefficient and many more with this name.

**Comment by AustinSanders** [comment] 2023-10-12 18:04
@Hplanet Thanks for updating -- maybe I missed the description the first time around.  This seems to be the same issue described at #5284.  We'll work on getting a proper fix in place, as this is not the intended behavior.  In the meantime, there appears to be a workaround posted on the other issue. 

I'm closing this as a duplicate issue, but you can track the status / add to the discussion at #5284.

**Closed as completed by AustinSanders** 2023-10-12 18:04 UTC
Labels: enhancement
