### ISSUE TITLE
spiceinit web service shape models

### ISSUE THREAD

**Issue by rwatkins15** [DOI-USGS/ISIS3#3453] opened 2019-09-16 16:19 UTC
**Description**  
I'd like to request a feature that allows the spiceinit web service to be used when the user specifies their own shape model (i.e., one not hosted by the web service). For example, I frequently process LROC NAC images using NAC DTMs as shape models, but right now the web service does not support this feature.

**Comment by jessemapel** [comment] 2019-09-16 16:22
See https://astrodiscuss.usgs.gov/t/processing-nac-images-with-nac-dtm-and-spiceinit-web/274 for more context

**Comment by jessemapel** [comment] 2020-04-03 19:44
I'm actually closing this as a duplicate of #1986

**Closed as completed by jessemapel** 2020-04-03 19:44 UTC
Labels: enhancement
