### ISSUE TITLE
Photomet allows `anglesource=DEM` when `normname=mixed`

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3452] opened 2019-09-16 15:51 UTC
**ISIS version(s) affected**: 3.9.0
Was an issue in 2017.  I am not a technical user and can no longer run ISIS3 to verify it is still an issue.

**Description**  

When setting normname=mixed, the algorithm must be applied to an ellipsoid shape model so a DEM can be calculated.  However, photomet allows the user to select anglesource=DEM.  

**How to reproduce**  

Open photomet gui.
Select normname=mixed
Select anglesource=DEM
Observe that no error/warning given to the user.  
Can do the same from the command line if you prefer.  

**Possible Solution**  

Remove DEM as a valid value for the anglesource parameter when normname=mixed.  
At least throw a warning to the user that the selected parameters are mutually incompatible and one of the who needs to be change.  

**Additional context**

**Comment by blandoplanet** [comment] 2019-10-07 22:02
This is still the case in ISIS3.9.0.

See Galileo test data in /work/users/mbland/Europa-data/Androgeos/

I was able "reproduce" using image 8600r_caltr.cub, which has been ingested, SPICED, calibrated, (and trimmed a bit - not necessary). The version *LLE_mixed.cub uses a Lambert model (for simplicity) and a "mixed" normalization with incref=30 incmat=70 thresh=1 and albedo=0.5. No errors or warning are given if anglesource=DEM see *LLE_mixed_DEM.cub). The same result is found if using the command line rather than the GUI..

However, using anglesource=DEM produces identical results to anglesource=ELLIPSOID, so I'm not sure this is actually a bug. If a DEM isn't provided it seems to default to ELLIPSOID. I don't have the data to test a DEM case.

Additionally, it's not clear to me from the docs why anglesource=DEM should be disallowed as long as the DEM covers the necessary spatial extent. My (limited) understanding is that this functionality simply permits ISIS to calculate more accurate photometric angles using a shape model. The mixed normalization tries to improve normalization at high incidence for global datasets. It's not obvious to me why using 'mixed' and anglesource=DEM together should be prohibited.

**Comment by lwellerastro** [comment] 2019-10-16 17:10
FYI - there is an image available under /work/projects/usertests/UserTestPlans/Apps/photomet/m04180/ which can utilize a DEM for testing.  I don't have permission to copy the input file over (all data in the directory are the output of tests), but I have confirmed it still exists.  See photomet-test.csh for commands and the location of the input file if there is interest in this data (apollo metric).  It could be useful for #3451 as well.

This storage area was an under-utilized attempt from the cartographers to better supply data and supporting tests for redmine posts, but it never really gained traction (no one used it).  There may be useful files here for other tests where data is not easily available.  See /work/projects/usertests/UserTestPlans/Data/.  It requires picking through some.

**Comment by jlaura** [comment] 2019-11-08 20:51
Closing this. Looks like the merge didn't close it. Nice work @ladoramkershner!

**Closed as completed by jlaura** 2019-11-08 20:51 UTC
Labels: bug, Products
