### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by ldx119** [DOI-USGS/ISIS3#4962] opened 2022-05-22 03:17 UTC
**ISIS version(s) affected**: x.y.z

**Description**  

Today I'm using the latest released version 3.1.0 of the Stereo Pipeline and I'm sure my installation steps are exactly the same as I did a few months ago . There was absolutely no problem with running it before, but today I tested whether my installation was successful and encountered such a problem.
I just use the command 'moc2isis' from .imq to .cub  , which has reported the error.
I also test the other tool , eg 'std2isis' , it also has this error.  
Is there a possible solution to this problem? Thanks.
![image](https://user-images.githubusercontent.com/100507049/169676698-4cb013d9-54cc-4b84-95c7-cb8afcb9cbe3.png)

**How to reproduce**  

**Possible Solution**  

**Additional context**  

<img width="437" alt="error-libraies" src="https://user-images.githubusercontent.com/100507049/169676734-e0fc45f1-d00b-415c-bbfa-d66b65aa16ae.PNG">

**Comment by jlaura** [comment] 2022-05-22 13:04
@ldx119 What version of ISIS are you running?

Also, please see: https://github.com/USGS-Astrogeology/ISIS3/issues/4951#issuecomment-1133707324

**Comment by ldx119** [comment] 2022-05-22 13:36
> @ldx119 What version of ISIS are you running?
> 
> Also, please see: [#4951 (comment)](https://github.com/USGS-Astrogeology/ISIS3/issues/4951#issuecomment-1133707324)

ISIS version is "isis=6.0.0"

**Comment by ldx119** [comment] 2022-05-22 14:00
> @ldx119 What version of ISIS are you running?
> 
> Also, please see: [#4951 (comment)](https://github.com/USGS-Astrogeology/ISIS3/issues/4951#issuecomment-1133707324)

I use the command which is "conda activate isis \
conda install -c conda-forge ffmpeg --force-reinstall" directly from #4951 but it didn't work.

Should I reinstall isis ? after this step" conda install -c usgs-astrogeology isis=6.0.0" and then I add the command "conda install -c conda-forge ffmpeg --force-reinstall" ?
<img width="403" alt="still" src="https://user-images.githubusercontent.com/100507049/169698866-b71f69bf-6868-4e80-b1b1-429c09bc016c.PNG">

thanks

**Comment by ldx119** [comment] 2022-05-22 14:50
> @ldx119 What version of ISIS are you running?
> 
> Also, please see: [#4951]
 I reinstall isis ,the version is 6.0.0 , add that command "conda install -c conda-forge ffmpeg --force-reinstall" after the "conda install -c usgs-astrogeology isis=6.0.0" , which is still the same error.

**Comment by oleg-alexandrov** [comment] 2022-05-23 03:24
The other issue is also suggesting something I tried myself, which is to install that offending library in a new environment, and copy it over. To go into more detail, one should first do:

conda create -c conda-forge -n tmptestenv ffmpeg=3.4.1

Then copy the library and its symlink with rsync (which should copy the symlinks properly):

rsync -avz ~/miniconda3/envs/tmptestenv/lib/libavresample.* ~/miniconda3/envs/isis6

assuming that your first environment is called 'tmptestenv' and second one is called 'isis6'. 

Or, just fetch https://conda.anaconda.org/conda-forge/linux-64/ffmpeg-3.4.1-0.tar.bz2, unzip it somewhere, and copy the lib from there.

This seems to be quite a quirky issue with conda. Not sure what its cause is.

**Comment by jessemapel** [comment] 2022-05-23 15:54
the conda-forge ffmpeg build has been having a lot of issues lately. Can you provide your whole conda environment? You can get it with `conda list`

**Comment by ldx119** [comment] 2022-05-24 02:27
> the conda-forge ffmpeg build has been having a lot of issues lately. Can you provide your whole conda environment? You can get it with `conda list`
ok the following is my 'conda list'
(isis) ldx@ubuntu:~$ conda list
# packages in environment at /home/ldx/anaconda3/envs/isis:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ale                       0.8.5            py36h605e78d_3    conda-forge
armadillo                 10.8.2               h7c03176_0    conda-forge
arpack                    3.7.0                hc6cf775_2    conda-forge
blas                      1.1                    openblas    conda-forge
boost                     1.68.0          py36h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bullet                    2.86.1                        0    usgs-astrogeology
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
csm                       3.0.3.3              hc9558a2_0    conda-forge
cspice                    66                h7f98852_1015    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
embree                    2.16.0                        0    usgs-astrogeology
expat                     2.4.8                h27087fc_0    conda-forge
ffmpeg                    3.4                  h7985aa0_0  
flann                     1.9.1                         0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
geos                      3.7.3                he1b5a44_0    conda-forge
geotiff                   1.4.3             hb6868eb_1001    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.51.4                        0    conda-forge
gmm                       5.0                           0    usgs-astrogeology
gmp                       6.2.1                h58526e2_0    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
inja                      3.3.0                h9c3ff4c_0    conda-forge
isis                      6.0.0                         0    usgs-astrogeology
jama                      125                           0    usgs-astrogeology
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
kakadu                    1                             0    usgs-astrogeology
krb5                      1.16.3            hc83ff2d_1000    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 11.2.0               h1234567_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgomp                   11.2.0               h1234567_0  
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libopenblas               0.3.18               hf726d26_0  
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libprotobuf               3.9.2                h8b12597_0    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              11.2.0               h1234567_0  
libtiff                   4.0.10            hc3755c2_1005    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvpx                    1.7.0                h439df22_0  
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mesalib                   18.3.1               h590aaf7_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mysql                     5.7.20            hf484d3e_1001    conda-forge
mysql-connector-c         6.1.11            hab6429c_1002    conda-forge
nanoflann                 1.4.2                ha770c72_0    conda-forge
ncurses                   6.3                  h7f8727e_2  
networkx                  2.5                        py_0    conda-forge
nlohmann_json             3.10.5               h9c3ff4c_0    conda-forge
nn                        1.86.0            h14c3975_2003    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.2.0           np113py36_blas_openblas_203  [blas_openblas]  conda-forge
openssl                   1.0.2u               h516909a_0    conda-forge
pcl                       1.9.1             h482114b_1002    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       21.2.2           py36h06a4308_0  
pixman                    0.34.0            h14c3975_1003    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     5.2.0             he1b5a44_1006    conda-forge
protobuf                  3.9.2            py36he1b5a44_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pvl                       1.3.1              pyhd8ed1ab_0    conda-forge
python                    3.6.7             hd21baee_1002    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h8f6f2f9_1    conda-forge
qhull                     7.2.0                         0    usgs-astrogeology
qt                        5.9.6                         7    usgs-astrogeology
qwt                       6.1.3                         0    usgs-astrogeology
readline                  7.0               hf8c457e_1001    conda-forge
scipy                     1.2.1            py36h09a28d5_1    conda-forge
setuptools                58.0.4           py36h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
spiceypy                  2.3.2                      py_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
superlu                   5.2.2                hfe2efc7_0    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
tk                        8.6.11               h1ccaba5_1  
tnt                       126                           0    usgs-astrogeology
tzcode                    2022a                h166bdaf_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
x264                      20131218                      0    conda-forge
xerces-c                  3.1.4                         0    usgs-astrogeology
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7f8727e_1  
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.12               h7f8727e_2  
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by ldx119** [comment] 2022-05-24 02:42
> The other issue is also suggesting something I tried myself, which is to install that offending library in a new environment, and copy it over. To go into more detail, one should first do:
> 
> conda create -c conda-forge -n tmptestenv ffmpeg=3.4.1
> 
> Then copy the library and its symlink with rsync (which should copy the symlinks properly):
> 
>rsync -avz ~/miniconda3/envs/tmptestenv/lib/libavresample.* ~/miniconda3/envs/isis6
> 
> assuming that your first environment is called 'tmptestenv' and second one is called 'isis6'.
> 
> Or, just fetch https://conda.anaconda.org/conda-forge/linux-64/ffmpeg-3.4.1-0.tar.bz2, unzip it somewhere, and copy the lib from there.
> 
> This seems to be quite a quirky issue with conda. Not sure what its cause is.


> The other issue is also suggesting something I tried myself, which is to install that offending library in a new environment, and copy it over. To go into more detail, one should first do:
> 
> conda create -c conda-forge -n tmptestenv ffmpeg=3.4.1
> 
> Then copy the library and its symlink with rsync (which should copy the symlinks properly):
> 
> rsync -avz ~/miniconda3/envs/tmptestenv/lib/libavresample.* ~/miniconda3/envs/isis6
> 
> assuming that your first environment is called 'tmptestenv' and second one is called 'isis6'.
> 
> Or, just fetch https://conda.anaconda.org/conda-forge/linux-64/ffmpeg-3.4.1-0.tar.bz2, unzip it somewhere, and copy the lib from there.
> 
> This seems to be quite a quirky issue with conda. Not sure what its cause is.
Sorry, I followed your instructions and still got the same error. I would like to explain my installation process in more detail:
step1：chmod +x Anaconda3-5.3.0-Linux-x86_64.sh
            ./Anaconda3-5.3.0-Linux-x86_64.sh
step2: here is a little different from the installation toturials ,what I have done is :  conda create -c conda-forge -n tmptestenv ffmpeg=3.4.1 ,which is follow your instruction.
step3:
  conda create -n isis python=3.6
  conda activate isis
  conda config --env --add channels conda-forge
  conda config --env --add channels usgs-astrogeology
  conda config --show channels
step4: conda install -c usgs-astrogeology isis=6.0.0
and then : rsync -avz ~/anaconda3/envs/tmptestenv/lib/libavresample.* ~/anaconda3/envs/isis

I'm sure the ISISDATA and ISISROOT is set properly : conda env config vars set ISISROOT=$CONDA_PREFIX ISISDATA=/home/ldx/anaconda3/envs/isis/data

So I don't know which step is wrong? Or is there someting I missing?

Thanks.

**Comment by oleg-alexandrov** [comment] 2022-05-24 04:00
My bad. I forgot to to add "lib" at the end. The command should be:

rsync -avz ~/miniconda3/envs/tmptestenv/lib/libavresample.* ~/miniconda3/envs/isis6/lib/

So, it should go from one "lib" to a second "lib".

**Comment by oleg-alexandrov** [comment] 2022-05-24 04:02
And I made another typo, yet again, which I later fixed above.

**Comment by oleg-alexandrov** [comment] 2022-05-24 04:04
Third time is the charm. Late here, can't think straight: rsync -avz ~/miniconda3/envs/tmptestenv/lib/libavresample.* ~/miniconda3/envs/isis6/lib

**Comment by ldx119** [comment] 2022-05-24 08:16
> 

Thank you very much for your help, the problem is completely solved！

**Comment by jessemapel** [comment] 2022-05-24 15:49
It appears the actual offender here is ffmpeg. Did you try `conda install -c conda-forge ffmpeg=3.4.1`?

**Comment by ldx119** [comment] 2022-05-25 03:48
> It appears the actual offender here is ffmpeg. Did you try `conda install -c conda-forge ffmpeg=3.4.1`?

I have tried ,using the command 'conda install -c conda-forge ffmpeg=3.4.1'. However ，it stucks on solving environmental problems , at least, it takes 3 hours.So,how long should it take for solving the environmental problems .
![image](https://user-images.githubusercontent.com/100507049/170175601-9c571277-d1e6-491d-8f99-4e28afa33610.png)

**Comment by planetarygeo** [comment] 2022-05-26 02:12
Hello - Thanks for our help on this issue.  I had the same problem trying a new installation of ISIS 6.0.0 today on Ubuntu 22.04 LTS, although I used the full anaconda.   I just wanted to say that I did try 
conda install -c conda-forge ffmpeg=3.4.1
and although it took a bit (not forever, maybe 10-15 min) it did eventually download/reinstall ffmpeg and it looks like installed something, updated something else, superceeded something and downgraded something.  Testing with qview it did open, but I got some additional errors (also the same errors when trying to open other functions):
![image](https://user-images.githubusercontent.com/6455389/170401140-734e0eb6-82b7-4d42-8376-e0d0888e8789.png)

Any thoughts on this would be appreciated.  Maybe it isn't a problem but I haven't gotten to do too much testing yet.  Thanks!

**Comment by oleg-alexandrov** [comment] 2022-05-26 02:59
Maybe more knowledgeable people will add to this, but your problem seems to be that you are running VMWare, and that your GUI's OpenGL library can't find the needed driver. That "vmwgfx" thing is apparently a kernel module.

The first question to ask is if you can open non-gui tools? For example, does "spiceinit" work, or some tools to convert PDS files to .cub? If not, that is quite bad, and likely GUI libraries like Qt and all the baggage they bring are too tied to the rest of ISIS. Hopefully not.

I wonder if you have access to another VM program. I've used for example VirtualBox for years and it seems to be working fine. Some people also use the Windows Subsystem for Linux.

Back to the issue itself, it is nasty and I never saw it before. There's a write-up here, but it is quite dense. https://lost-contact.mit.edu/afs/pdc.kth.se/roots/ilse/v0.7/pdc/vol/mesa/9.2.5/src/Mesa-9.2.5/docs/vmware-guest.html

**Comment by planetarygeo** [comment] 2022-05-26 16:22
Hi Oleg,

Thanks for your helpful thoughts and the link.  It does seem like it is something with vmware rather than ISIS, so apologies for posting it here, but perhaps someone else will still run into the same problem ;).   I have used vmware quite a bit in the past but this is a totally new setup with a new version of everything :P.  So probably there is a setting/bug somewhere that I need to adjust :).  I will keep working on it!

~Kelsi

**Comment by jessemapel** [comment] 2022-07-05 17:01
I am going to close this as we're not able to locally test on vmware systems to reproduce and similar issues have been resolved by the new ffmpeg builds. If anyone else encounters this problems please post here.

**Closed as completed by jessemapel** 2022-07-05 17:01 UTC
Labels: bug
