### ISSUE TITLE
GitHub Tutorials Missing

### ISSUE THREAD

**Issue by SPIFdmZPonterio** [DOI-USGS/ISIS3#4160] opened 2020-12-02 18:03 UTC
Many of the tutorials on this page are coming up "404 file not found". Anyone know what's happened to them?

**Comment by jessemapel** [comment] 2020-12-02 18:12
Can you be more specific about where you are looking for the tutorials and which tutorials are erroring?

**Comment by jessemapel** [comment] 2020-12-02 18:16
potentially duplicate of #4083

**Comment by SPIFdmZPonterio** [comment] 2020-12-02 18:22
I'm clicking on the links on the right side of the wiki tab on this page under "Tutorials". The ones that aren't working are under the first two headings, "Fundamentals" and "General Image Processing", and they are: ISIS Cube Format, Core Base and Multiplier, Special Pixels, The Power of Spatial Filters, and Removing Striping Noise.

**Comment by jessemapel** [comment] 2020-12-02 18:30
Actually a duplicate of #3441, I'm going to look into this but will be updating over there.

**Closed as completed by jessemapel** 2020-12-02 18:30 UTC
Labels: documentation

**Comment by jessemapel** [comment] 2020-12-02 22:25
The links should all be fixed now
