### ISSUE TITLE
Conda installation fails on libtiff dependency

### ISSUE THREAD

**Issue by kbowley-asu** [DOI-USGS/ISIS3#636] opened 2018-12-09 16:09 UTC
Attempting to install isis3 with the conda installation instructions results in the following:
```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - isis3
  - libtiff==4.0.9=0
```
It appears that libtiff==4.0.9=0 is not available.
```
$ conda search libtiff==4.0.9
Loading channels: done
# Name                  Version           Build  Channel             
libtiff                   4.0.9      h28f6b97_0  pkgs/main           
libtiff                   4.0.9      he6b73bb_1  conda-forge         
libtiff                   4.0.9      he6b73bb_2  conda-forge         
libtiff                   4.0.9      he85c1e1_1  pkgs/main           
libtiff                   4.0.9      he85c1e1_2  pkgs/main
```

**Comment by jlaura** [comment] 2018-12-09 16:25
@kbowley-asu What OS are you on?

**Comment by kbowley-asu** [comment] 2018-12-09 16:50
I've had the same result on Ubuntu 16.04, Ubuntu 18.04, and Mac 10.13.5

**Comment by kbowley-asu** [comment] 2018-12-09 16:51
This is starting with a fresh install of Miniconda on each platform.

**Comment by jlaura** [comment] 2018-12-09 16:56
I wonder if this is due to the environment.yml hard pinning, e.g., environment.yml: `libtiff==4.0.9=0` to `libtiff>=4.0.9`. I wonder if the issue is that the build number is being specified and that build number has been purged from conda-forge. 

We also have an open issue (#615) where we have been discussing the hard pinning to dependencies. I think that this is likely what you are encountering.

I will give this a test and a build on my Mac and see if that is the issue. If so, we can get a PR in to update the environment.yml after all of the tests have been executed.  Thanks for reporting!

**Comment by camisatx** [comment] 2018-12-14 18:37
Hey @jlaura, thanks for all the great work you and the team do! Did you have any luck reproducing and testing this?

I experienced the same conda installation failure as @kbowley-asu described above, with conda failing to find `isis3` and `libtiff==4.0.9=0`.

I am using Ubuntu 18.04.1 and Anaconda 5.3 (Python 3).

**Comment by seignovert** [comment] 2018-12-14 18:56
Exactly the same issue here on Centos7 and Fedora27.
Changing the `environment.yml` to `libtiff>=4.0.9` should fix it.

Side note: the lastest version of `libtiff` is now `4.0.10`.

**Comment by jessemapel** [comment] 2018-12-14 21:21
@camisatx Last I checked @jlaura was working on this, but he's going to be in and out of the office over the holidays.

I am able to re-produce this error. We're planning to push out 3.6.1 sometime next week. I'm going to check the pr from @seignovert and hopefully it can go out with 3.6.1

**Comment by jlaura** [comment] 2018-12-14 21:47
@camisatx @jessemapel I am in and out. I got a build going with this, but was getting errors from the geos library when I unpinned liftiff. I am in next week to have another go at this.

**Comment by jessemapel** [comment] 2018-12-14 22:02
For future reference, fixing the ISIS3 build environment files will only fix problems for people making new build environments. We need to update the ISIS3 conda build recipe in a similar fashion and push up a brand new 3.6.0 build. Only then, will the Anaconda runtime requirements for installing ISIS3 be fixed.

**Comment by jessemapel** [comment] 2018-12-17 18:20
This has been fixed for the ISIS3 build environment but it's going to take a whole new release. We're planning to fix this for all of our dependencies and then push a new build out. That should happen in a week or two depending on holidays, etc.

Watch for 3.6.1

**Comment by jessemapel** [comment] 2018-12-21 22:45
This should now be fixes 🎉 

Go ahead and re-try installing now. You'll get version 3.6.1 which is 3.6.0 with a fix for this and a fix for a bug in cubeit.

**Comment by jessemapel** [comment] 2018-12-21 22:48
I recommend you clear out your anaconda package cache prior to installing. Run `conda clean --all` in both your base environment and the environment you are installing ISIS into. This will cause Anaconda to re-download all of the packages, and will make your install take more time based on how fast your connection is (it's about 2 GB of dependencies).

**Comment by camisatx** [comment] 2018-12-21 23:19
Installed successfully on my Ubuntu 18.04 machine. I appreciate the work and thanks for the early Christmas present! *<:-)

**Comment by jlaura** [comment] 2018-12-22 02:01
@jessemapel Awesome job! I am going to close. @kbowley-asu please reopen if you still have an issue.

**Closed as completed by jlaura** 2018-12-22 02:01 UTC
Labels: build
