### ISSUE TITLE
EmbreeTargetManager unitTest uses local data

### ISSUE THREAD

**Issue by jessemapel** [DOI-USGS/ISIS3#3513] opened 2019-11-15 18:01 UTC
The EmbreeTargetManager unitTest uses local test data at the ASC. This causes it to fail on the external Jenkins tests.

**Comment by ladoramkershner** [comment] 2019-11-15 19:30
I (and by 'I' I mean @acpaquette) am fairly confident that this failure is caused by the failure of the preceding tests (issue #3511 and #3512). I will close this for now, but it can be reopened if it continues to fail.

**Comment by ladoramkershner** [comment] 2019-11-18 22:11
I was wrong. PR #3545

**Closed as completed by ladoramkershner** 2019-11-18 22:11 UTC
