### ISSUE TITLE
Issue with camera model not found

### ISSUE THREAD

**Issue by mun-mn** [DOI-USGS/ISIS3#5530] opened 2024-06-24 11:03 UTC
Hello,
I have ingested a mrf image , formed a cube. While processing the spiceinit command, with web=yes, I come across the particular error with ".tls' file not found. I have attached a screenshot of the error as well. 
please suggest a solution 
Thanks in advance 
![Screenshot from 2024-06-24 16-13-50](https://github.com/DOI-USGS/ISIS3/assets/173681707/ca688bf1-5f2e-4d2b-a56d-52938d79c548)

Thanks!

**Comment by Kelvinrr** [comment] 2024-06-27 20:16
Sounds like you need to setup the base data area https://github.com/DOI-USGS/ISIS3?tab=readme-ov-file#the-isis-data-area

**Comment by mun-mn** [comment] 2024-06-30 13:16
Yes, it has been solved. Thanks !! 

But, now I have encountered an issue in the cam2map step. The error is "**terminate called after throwing an instance of 'std::invalid_argument'
  what():  Error in evaluating cubic hermite velocities, values atlower and upper indicies are exactly equal.
Aborted (core dumped)"**

Note: I used all the default parameters in the cam2map step

Any suggestions/solutions on this one ?

**Comment by CaoimheMor** [comment] 2024-07-01 09:53
Good morning,
I have encountered a very similar problem, so I thought I'd add it here instead of opening a new and potentially duplicate issue.

Here are the details:
The base kernels issue I figured out, however, upon running spiceinit, I also obtain the lines: 
"**ERROR** The SPICE server returned incompatible SPICE data.
**ERROR** Unable to initialize camera model in Camera Factory."
Note: the first line only appears when requesting spice data from server. The second one does too, however, I've encountered it in different contexts and seems tied to the error.
It then continues on with:
**ERROR** Unable to locate latest camera model version number from group [Instrument].
"**ERROR** Unsupported camera model, unable to find plugin for SpacecraftName [JUNO] with InstrumentId [JNC].
**ERROR** Unable to find PVL group [JUNO/JNC]."
I have a file folder within $ISISDATA/juno containing a CameraPlugin file and some other code files.
The contents of the Instrument group are given by junocam2juno, so I imagine they aren't the issue (InstrumentHostID is set to unknown, but even changing that didn't help).

I would appreicate your input on the matter.
If the solution is to update the base and/or mission specific files, is there a way of installing only the missing files rather than running the entire installation?

Thank you for your time!

**Comment by Kelvinrr** [comment] 2024-07-01 15:54
I would also suggest downloading the mission specific area, it's possible there is a missing file during spiceinit. But if you managed to spiceinit successfully, I imagine you already downloaded the mission specific data.

**Comment by mun-mn** [comment] 2024-07-02 07:14
Hello Sir @Kelvinrr  I have encountered an issue in the cam2map step. The error is "terminate called after throwing an instance of 'std::invalid_argument'
what(): Error in evaluating cubic hermite velocities, values atlower and upper indicies are exactly equal.
Aborted (core dumped)"

Note: I used all the default parameters in the cam2map step

Any suggestions/solutions would be appreciated.
Thank you for your time Sir

**Comment by CaoimheMor** [comment] 2024-07-02 12:29
> I would also suggest downloading the mission specific area, it's possible there is a missing file during spiceinit. But if you managed to spiceinit successfully, I imagine you already downloaded the mission specific data.

Thank you for your response.
I haven't managed to run spiceinit, although I do get an output when I use Web Spice kernels that seems coherent with the example output given in the ISIS Documentation. However, it's not completely succesful, as for instance caminfo and cam2map produce the same error when run on the file, and qview will not display coordinates and say that a camera or projection file is needed. I believe the mission specific file is up to date. Do you have any other solutions?
Thank you!

**Comment by Kelvinrr** [comment] 2024-07-02 16:19
@CaoimheMor and @mun-mn 

can you both provide minimum examples of how to reproduce this? That way it can be easier to debug.

**Comment by CaoimheMor** [comment] 2024-07-03 09:51
Hello,
Sorry, I'm new to Github, I'm not entirely sure what would be useful to you, but I'll tell you what I can...

The error is:

**ERROR** Unable to initialize camera model in Camera Factory.
**ERROR** Unable to locate latest camera model version number from group [Instrument].
**ERROR** Unsupported camera model, unable to find plugin for SpacecraftName [JUNO] with InstrumentId [JNC].
**ERROR** Unable to find PVL group [JUNO/JNC].

The error appears when:
Running spiceinit (default options)
Running caminfo (default options)
Running cam2map (default options)

Here is an example of concrete data from the process:
In order of appended files:

- The original rdr data label as txt file (Accessible with the IMG file at https://planetarydata.jpl.nasa.gov/img/data/juno/JNOJNC_0017/DATA/RDR/JUPITER/ORBIT_31/ ) 
- One of the junocam2isis processed framelets (under text file format for github)
- A duplicate of this framelet (also as text file) after using SPICE web server with spiceinit's default options: 
	- Note: while it does return the error above (as well as saying that SPICE data is incompatible), it does append the kernel group / produce an output - when running on local, spiceinit just produces the error and stops. 
	- Note 2: I posess on local all of the kernels suggested by the web service other than the ck kernel, which doesn't seem available on the NAIF index. Using nadir gives the same error.

Additional note on your previous answer:
After some thinking, it's possible I obtained the kernels elsewhere then through DownloadISISdata, so it's possible that the mission specific files aren't up to date, but running DownloadIsisData juno with the --no-kernels option transfers 0 bytes then terminates, which I would take to mean that they are complete.
However, DowloadIsisData is giving me its own set of issues so I can't be sure... 
I don't really know what is supposed to be contained in the mission specific data outside of the kernels, but if it includes camera or CMS plugins then maybe that's the source. That would then require further debugging...

Thank you for your time!


[JNCR_2020365_31C00006_V01.txt](https://github.com/user-attachments/files/16081259/JNCR_2020365_31C00006_V01.txt)
[JNCR_2020365_31C00006_V01_RED_0028.txt](https://github.com/user-attachments/files/16081264/JNCR_2020365_31C00006_V01_RED_0028.txt)
[JNCR_2020365_31C00006_V01_RED_0028 - Copy (2).txt](https://github.com/user-attachments/files/16081265/JNCR_2020365_31C00006_V01_RED_0028.-.Copy.2.txt)

**Comment by CaoimheMor** [comment] 2024-07-04 07:08
Hello!
I fixed the issue!
Turns out that Camera.plugin, libjuno.so and libjunocamera.so (and every other camera libary) were installed in anaconda3/envs/isis/lib instead of $ISISROOT/lib ! Copying them over to the correct directory fixed this issue (and now I have new ones, but I'll try to fix those on my own first).
Thank you for your help!

**Comment by mun-mn** [comment] 2024-07-05 17:39
Hello @Kelvinrr 
I am stuck in the cam2map process. I have attached the screenshots of the steps I have followed. I have successfully completed the "reduction of 4 band stacked, cleaned cube to approximately 15meters/pixel.
But, after this step, Iam not able to proceed with the cam2map step. I am getting the following error.
![03](https://github.com/DOI-USGS/ISIS3/assets/173681707/093c0a90-5399-4bbc-ac46-3e2e7ae215a9)
Steps followed in the cam2map step is attached as well below:
![01new](https://github.com/DOI-USGS/ISIS3/assets/173681707/e898b871-5828-4f98-9c79-0ebaae352247)
![02new](https://github.com/DOI-USGS/ISIS3/assets/173681707/ea3909a6-d8e6-4f2d-a5a4-842103cbaf17)

I would really appreciate your time and suggestions for solving this error.
Thank you in advance.

**Closed as completed** 2024-07-09 16:54 UTC
Labels: documentation
