### ISSUE TITLE
spiceinit error

### ISSUE THREAD

**Issue by Ben-Bussey** [DOI-USGS/ISIS3#4029] opened 2020-09-22 19:04 UTC
**ISIS version(s) affected**: 4.2.0

**Description**  
When trying to run spiceinit on a LROC WAC image, using the web kernels, I am getting an error

**How to reproduce**  
When I run spiceinit with web=yes, I get an error saying the spice server only supports versions more recent than 3.5, and that I have 4.2?
![Screen Shot 2020-09-22 at 1 46 31 PM](https://user-images.githubusercontent.com/71727412/93925919-dbe23700-fce4-11ea-8af5-de890dfe1a6b.png)

**Possible Solution**  
I guess I can install the pro kernels directly onto my laptop?
**Additional context**

**Comment by jessemapel** [comment] 2020-09-22 19:42
Duplicate of #3725 

@Ben-Bussey There is a work around for right now: https://github.com/USGS-Astrogeology/ISIS3/issues/3725#issuecomment-619091103

You could also download the kernels if that doesn't work for you. Note that the workaround will cause your print.prt and Cube histories to list the wrong version of ISIS, but besides that it won't change any outputs.

**Closed as completed by jessemapel** 2020-09-22 19:42 UTC

**Comment by Ben-Bussey** [comment] 2020-09-22 19:43
Thank you.

Just fyi, I did search issues for “spiceinit” and didn’t see the one you sent.  Apologies if I should have found it.

Ben

**Comment by jessemapel** [comment] 2020-09-22 21:58
@Ben-Bussey Don't worry, github's search is notoriously terrible!

**Comment by jlaura** [comment] 2020-09-29 18:35
A fix has been deployed and should be working. See the previously linked issue #3725 as this fix does not have an immediately associated PR. 

https://github.com/USGS-Astrogeology/ISIS3/issues/3725#issuecomment-700886497
