### ISSUE TITLE
Cannot Read MRF S Band IMG or LBL data

### ISSUE THREAD

**Issue by GavinT94** [DOI-USGS/ISIS3#3235] opened 2019-04-17 17:08 UTC
I have installed ISIS3 to my Mac lab computer and downloaded the LRO data sets, kernels excluded. I am trying to convert MRF S Band IMG and LBL data to an isis cube format but I always get this error **I/O ERROR** Unable to read [DATA_SET_ID] from input file [sband_12n333_cpr.img].

I am still new to using ISIS3 but I was wondering if there is anything I am missing?

Cheers,

**Comment by jlaura** [comment] 2019-04-17 19:04
@GavinT94 This looks like a question and not a bug report. Can you please open this on our [Astrodiscuss](https://astrodiscuss.usgs.gov/) Q/A forum?

I am going to close this for now, but please reopen if this is a bug with the software and you can indicate that either the problem is intermittent or how to reproduce. Thanks!

**Closed as completed by jlaura** 2019-04-17 19:04 UTC

**Comment by krlberry** [comment] 2019-04-17 22:10
@GavinT94 I created a post for this on astrodiscuss at https://astrodiscuss.usgs.gov/t/cannot-read-mrf-s-band-img-or-lbl-data/168 and posted a question and a potential solution there.

**Comment by thareUSGS** [comment] 2019-04-23 14:31
please above link on the discussion site - hopefully it will help.
