### ISSUE TITLE
kaguyatc2isis

### ISSUE THREAD

**Issue by benjabul** [DOI-USGS/ISIS3#4663] opened 2021-11-02 17:51 UTC
**ISIS version(s) affected**: 4.0

**Description**  
I am using ISIS3 updated just today (02/11/2021) installed on a windows machine with Ubuntu18.04LTS.
When I run kaguyatc2isis on the image I downloaded I get an error related to the change of Product_ID that was done in the new version of the KaguyaTC images in 2019. 
I saw that the way this problem was solved by the isis team is to use the .lbl and not the .img. I tried that and I still get an error because the path took to look for the .img is missing a "/". Instead of looking for mnt/c/../work/KaguyaTC/TCO_MAPm04_N45E306N42E309SC.img' it looks for  mnt/c/../work/KaguyaTCTCO_MAPm04_N45E306N42E309SC.img.
I tried to process an image located in my isis3 directory to not have to go out of the "UBUNTU" part. I still got an error:
**I/O error** unable to open [TCO_MAPm04_N45E306N42E309SC.lbl]

**How to reproduce**  
kaguyatc2isis

**Comment by jlaura** [comment] 2021-11-02 20:44
@benjabul Would you mind providing a download link to the file? I have been processing a lot of Kaguya TC (2C2 data) and the file name you are providing is not one that I have ever encountered with the data. A link to DARTs where the file is available would help me reproduce the error.

Thanks!
J

**Comment by benjabul** [comment] 2021-11-02 20:49
sure: https://data.darts.isas.jaxa.jp/pub/pds3/sln-l-tc-5-morning-map-v4.0/lon306/data/TCO_MAPm04_N45E306N42E309SC.img

**Comment by benjabul** [comment] 2021-11-03 08:50
update: I found a way to fix this but I guess you may have an easy way to fix the code itself.
I modifed the .lbl by changing the DATA_SET_ID to "TC2_Level2B". I also change the FILE_NAME to"/TCO_MAPe04_N45E306N42E309SC.img" (the "/" was added). Then I also needed to chmod u+rx,go-w some of the directories but this last part is probably specific to my architecture.

**Comment by jlaura** [comment] 2021-11-03 13:07
@benjabul I am not able to reproduce the errors that you are seeing. I tested on ISIS6.0.0 and ISIS4.3.0 on OSX. 

I downloaded the cub and lbl files that you linked and then ran:

```bash
kaguyatc2isis from=TCO_MAPm04_N45E306N42E309SC.lbl to=TCO_MAPm04_N45E306N42E309SC.cub
qview TCO_MAPm04_N45E306N42E309SC.cub
```

no errors and here is the result:
<img width="667" alt="Screen Shot 2021-11-03 at 6 04 53 AM" src="https://user-images.githubusercontent.com/2105468/140065344-4b1fd32f-38d0-4d18-a10b-ad8397938e20.png">


Is this the output that I should be expecting? If so, what OS are you on? The path issue that you have identified is strange I wonder if something else isn't going on with your environment.

**Comment by benjabul** [comment] 2021-11-04 06:00
Yes this is what is supposed to be produced. I guess then it comes from me. I have on very recent windows 10 but run Ubuntu18.04LST installed via the microsoft store. I followed the procedure from [this](https://www.willyingling.com/research-blog/2019/5/9/how-to-installing-isis3-on-a-windows-computer) to install ISIS3 and I did it 3 days ago.

**Comment by jlaura** [comment] 2021-11-04 12:41
@benjabul I am not familiar with those installation instructions though, from your reports it sounds like the issues you are seeing are a local problem caused by paths, e.g., something is not mounted properly between windows and the ubuntu subsystem. 

I am going to close this issue for now as I can not reproduce. If you have another issue with kaguyatc2isis and these data, please feel free to reopen! If you find any other bugs, we definitely appreciate your contribution to the tracker, so get those opened and we will get looking at them. Thanks!

**Closed as completed by jlaura** 2021-11-04 12:41 UTC
