### ISSUE TITLE
openssl error when installing ISIS with mamba

### ISSUE THREAD

**Issue by valemercurii** [DOI-USGS/ISIS3#4801] opened 2022-02-15 09:49 UTC
Hi,
I'm not sure whether this is the right place to ask but, I have installed Ubuntu 20.04 WSL on Windows 11 and when trying to install isis with `mamba` I get the following error:
```
Looking for: ['isis']

usgs-astrogeology/noarch [====================] (00m:00s) Done
usgs-astrogeology/linux- [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:02s) Done
conda-forge/linux-64     [====================] (00m:07s) Done
Encountered problems while solving.
Problem: package python-3.6.13-h12debd9_1 requires openssl >=1.1.1k,<1.1.2a, but none of the providers can be installed
```
Does anyone of you know how to solve this?

EDIT: I solved it by installing isis with `conda`, however, the above problem remains.

Thanks for your help,
Vale

**Comment by jlaura** [comment] 2022-02-15 13:20
@valemercurii What does your installation command look like? I suspect `mamba install isis` and not `mamba install isis=6.0.0`?

**Comment by valemercurii** [comment] 2022-02-15 13:23
@jlaura Yes, I used simply `mamba install -c usgs-astrogeology isis` as written in the instructions section

**Comment by jlaura** [comment] 2022-02-15 13:33
@acpaquette @Kelvinrr @jessemapel @scsides @AustinSanders 

It looks like the installation is not trying to get the latest version of ISIS unless the version is explicitly specified? If that is correct, can we please update the installation instructions and/or fix the package uploads so that mamba install isis gets the latest version

**Comment by scsides** [comment] 2022-02-15 19:11
This looks like I caused it with an upload that isn't properly marked as RC. I'll fix it.

**Comment by scsides** [comment] 2022-02-16 07:11
The offending file has been removed, but a test install of 6.0.0 is failing with the same error. Still looking into the cause.

**Comment by jessemapel** [comment] 2022-03-16 15:55
This sort of behavior has been identified as working as expected for conda. So, there's nothing we can do as conda will always prefer older versions with fewer dependencies.

https://github.com/conda/conda/issues/2011

**Closed as completed by jessemapel** 2022-03-16 15:55 UTC
