### ISSUE TITLE
spice server error text

### ISSUE THREAD

**Issue by lavalaz** [DOI-USGS/ISIS3#3855] opened 2020-05-01 21:11 UTC
**ISIS version(s) affected**: x.y.z
4.0.0
**Description**  

See the text
**How to reproduce**  

run spiceinit with use the web service clicked
**Possible Solution**  

**Additional context**  

![image](https://user-images.githubusercontent.com/43523454/80842070-8e3e2400-8bb5-11ea-9322-3253e5dafb3c.png)

**Comment by jessemapel** [comment] 2020-05-01 21:16
Duplicate of #3725

**Comment by jessemapel** [comment] 2020-05-01 21:17
We have a solution for this, but it hasn't been deployed yet on the server end :(

**Closed as completed by jessemapel** 2020-05-01 21:16 UTC
