### ISSUE TITLE
Campt rounding error on round trip projection

### ISSUE THREAD

**Issue by ladoramkershner** [DOI-USGS/ISIS3#4069] opened 2020-10-13 20:21 UTC
**ISIS version(s) affected**: x.y.z
isis3.9.1 but presumably all version are affected

**Description**  

If you use campt to go from an image down to the ground and back (or vise versa), you do not receive the values you started with. I am not sure if this is an expected behavior or a known error, but it is messing with affine transformations in autocnet and even just some clarification on the expected behavior would be helpful!

**How to reproduce**  

IMAGE-GROUND-IMAGE
`campt from=/scratch/ladoramkershner/mars_quads/oxia_palus/updated/P17_007652_1843_XN_04N026W.cal.cub type="image" sample=200 line=200`
returns:
```
PlanetocentricLatitude     = 1.6863152154313 <DEGREE>
PositiveEast360Longitude   = 333.39770288546 <DEGREE>
```
Using PlanetocentricLatitude and PositiveEast360Longitude
`campt from=/scratch/ladoramkershner/mars_quads/oxia_palus/updated/P17_007652_1843_XN_04N026W.cal.cub type="ground" latitude=1.6863152154313 longitude=333.39770288546`
returns:
```
Sample                     = 200.00002225147
Line                       = 200.00000097857
```

GROUND-IMAGE-GROUND
`campt from=/scratch/ladoramkershner/mars_quads/oxia_palus/updated/P17_007652_1843_XN_04N026W.cal.cub type="ground" latitude=1.68 longitude=333.4`
returns:
```
Sample                     = 216.96140355769
Line                       = 135.22426426684
```
Then
`campt from=/scratch/ladoramkershner/mars_quads/oxia_palus/updated/P17_007652_1843_XN_04N026W.cal.cub type="image" sample=216.96140355769 line=135.22426426684`
returns:
```
PlanetocentricLatitude     = 1.680000000246 <DEGREE>
PositiveEast360Longitude   = 333.40000000163 <DEGREE>
```

**Comment by jessemapel** [comment] 2020-10-13 20:32
@ladoramkershner Can you run camstats to get the pixels per degree resolution of the image?

**Comment by ladoramkershner** [comment] 2020-10-13 22:16
I cannot find a pixels per degree resolution output or option for camstats

**Comment by jessemapel** [comment] 2020-10-13 23:00
There should be a pixel resolution value in the campt/camstats output. It may or may not be in PPD. What do you get for that value?

**Comment by ladoramkershner** [comment] 2020-10-13 23:23
It is in MPP. Here are the general stats, they also break them up by line and sample.

```
Group = Resolution
  ResolutionMinimum           = 5.3998208180121 <meters/pixel>
  ResolutionMaximum           = 5.4958319966856 <meters/pixel>
  ResolutionAverage           = 5.453855314073 <meters/pixel>
  ResolutionStandardDeviation = 0.027196886824302 <meters/pixel>
End_Group
```

**Comment by jessemapel** [comment] 2020-10-13 23:41
Converting to degrees per pixel that's about 0.0001 which doesn't seem to be accounting for the difference. Not sure what is going on here 🤔

**Comment by ladoramkershner** [comment] 2020-10-13 23:47
Additionally, if it was a resolution issue shouldn't the latitude/longitude resulting from the input line/sample either fall into the same rounding bin or result in the same interpolation when it comes back to line/sample?

**Comment by jlaura** [comment] 2020-10-15 14:20
Tested in 4.3.0-RC1 because #3928 was merged and I was wondering if that could have anything to do with the problem we are seeing.

### Image to Ground
`campt from=/scratch/ladoramkershner/mars_quads/oxia_palus/updated/P17_007652_1843_XN_04N026W.cal.cub type="image" sample=200 line=200`

```
  Sample                     = 200.0
  Line                       = 200.0
  PixelValue                 = 0.11753853
  RightAscension             = 185.18430472394 <DEGREE>
  Declination                = 24.695465953841 <DEGREE>
  PlanetocentricLatitude     = 1.6863152154313 <DEGREE>
  PlanetographicLatitude     = 1.7063314263807 <DEGREE>
  PositiveEast360Longitude   = 333.39770288546 <DEGREE>
```

### Ground to Image
`campt from=/scratch/ladoramkershner/mars_quads/oxia_palus/updated/P17_007652_1843_XN_04N026W.cal.cub type="ground" latitude=1.6863152154313 longitude=333.39770288546`

```
  Sample                     = 200.0000222515
  Line                       = 200.00000097857
  PixelValue                 = 0.11753853
  RightAscension             = 185.1843047239 <DEGREE>
  Declination                = 24.69546595386 <DEGREE>
  PlanetocentricLatitude     = 1.6863152154313 <DEGREE>
  PlanetographicLatitude     = 1.7063314263807 <DEGREE>
  PositiveEast360Longitude   = 333.39770288546 <DEGREE>
```

So, it looks like this is not an issue related to #3928. 😦

**Comment by jessemapel** [comment] 2020-10-15 16:51
Okay, this looks like expected behavior. The ground to image process involves an iterative inversion of the distortion model that uses a tolerance of 0.01 pixels. So, this type of accuracy is expected. I am going to run a quick test disabling distortion to see if it is accounting for the majority of the error.

**Comment by jessemapel** [comment] 2020-10-15 17:19
Some testing results. I set all of the OD_K values in the naif_keywords to 0, which disables distortion. Repeating Lauren's first test I got this:

### Image -> Ground -> Image

```
campt from=P17_007652_1843_XN_04N026W.cal.no_dist.cub type="image" sample=200 line=200
```

```
    PlanetocentricLatitude     = 1.6862835845899 <DEGREE>
    PositiveEast360Longitude   = 333.39744337182 <DEGREE>
```

```
campt from=P17_007652_1843_XN_04N026W.cal.no_dist.cub type="ground" latitude=1.6862835845899 longitude=333.39744337182
```

```
    Sample                     = 199.99999995795
    Line                       = 200.00000097857
```

### Ground -> Image -> Ground

```
campt from=P17_007652_1843_XN_04N026W.cal.no_dist.cub type="ground" latitude=1.68 longitude=333.4
```

```
    Sample                     = 219.48725144742
    Line                       = 135.22467708537
```

```
campt from=P17_007652_1843_XN_04N026W.cal.no_dist.cub type="image" line=135.22467708537 sample=219.48725144742
```

```
    PlanetocentricLatitude     = 1.6799999990817 <DEGREE>
    PositiveEast360Longitude   = 333.40000000011 <DEGREE>
```

Still a small difference of around 10 digits which could come from lots of places but seems reasonable. The other source of error from an iterative method would be the DEM. So, More testing with an ellipsoid shapemodel that won't have that iterative error.

### Image -> Ground -> Image

```
campt from=P17_007652_1843_XN_04N026W.cal.no_dist.no_dem.cub type="image" sample=200 line=200
```

```
    PlanetocentricLatitude     = 1.686600478591 <DEGREE>
    PositiveEast360Longitude   = 333.39941289486 <DEGREE>
```

```
campt from=P17_007652_1843_XN_04N026W.cal.no_dist.no_dem.cub type="ground" latitude=1.686600478591 longitude=333.39941289486
```

```
    Sample                     = 200.00000000036
    Line                       = 200.00000097857
```

About the same, so it doesn't seem like the DEM is a source of significant error.

This is one of those fundamental assumptions in ISIS. Iterative solutions and approximations all use 0.01 pixels for a tolerance. With something like CSM, the tolerance is a parameter that gets passed in, but not in ISIS.

**Comment by jessemapel** [comment] 2020-10-15 17:20
Closing as expected behavior. The camera models are just not designed to be this accurate.

**Closed as completed by jessemapel** 2020-10-15 17:20 UTC
Labels: wontfix

**Comment by jlaura** [comment] 2020-10-16 15:09
Is rounding a valid solution then? If so, to what significant digit?

**Comment by jessemapel** [comment] 2020-10-16 15:46
For CTX, you should expect accuracy to 0.01 pixels
