### ISSUE TITLE
Conda glibc dependency conflict when installing isis=7.0.0

### ISSUE THREAD

**Issue by islamomar97** [DOI-USGS/ISIS3#5238] opened 2023-07-12 18:56 UTC
**ISIS 7.0.0**

**Description**  
whenever I'm trying to install isis=7.0.0 I get the following error even though I tried Ubuntu 18.04, 20.04, and 22.04

$ conda install -c usgs-astrogeology isis=7.0.0

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - isis=7.0.0 -> mesalib -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.35

**Comment by acpaquette** [comment] 2023-07-17 19:30
@islamomar97 This is a larger issue with some of the ISIS releases not having good pinning on dependencies. I would try creating a new env but removing the `isis=7.0.0` and just try installing `isis` with no versioning

**Comment by islamomar97** [comment] 2023-07-17 19:45
I have already tried this and even specific older versions and still had the same issue

**Comment by antonhibl** [comment] 2023-11-16 23:20
I have just tested this on a new ubuntu instance and confirmed that Adam's advice to install ISIS without specifying a version works without any errors for dependent packages. Like Adam said there is a known issue with pinning dependent package versions for previous versions of ISIS, this is why you run into issues when specifying 7.0.0; @islamomar97  I would double check to ensure you are following the installation documentation guide at https://github.com/DOI-USGS/ISIS3/blob/dev/README.md#Installation and you shouldn't see any more errors while installing the current ISIS version that way. Internal discussions are being raised on how to solve this problem with previous versions dependencies and whether this will be a continual point of focus going forward.

**Comment by islamomar97** [comment] 2023-11-16 23:24
Thanks for getting back to me. I did try it several times and even one of my friends did as well. Would you please clarify if you did make any changes since the time I did email you? Thanks.

Islam


Thanks & Regards,



[Logo  Description automatically generated]Islam Omar

Research Assistant

Electrical & Computer Engineering

NMSU, Knox Hall #305

***@***.***

[A picture containing paper clip, tool  Description automatically generated](575) 805 – 9676

[Logo  Description automatically generated]<https://www.linkedin.com/in/islam-omar-a42560110/>Islam Omar<https://www.linkedin.com/in/islam-omar-a42560110/>



[X]



________________________________

**Comment by antonhibl** [comment] 2023-11-16 23:54
@islamomar97 If it was still failing when trying to install without specifying the ISIS version as a previous version then it's possible changes were made that your local environment hasn't pulled yet, you should be able to update your local repository using `git fetch --all` and `git pull <name of remote for USGS ISIS repository(most likely just origin)>`. Otherwise there may be a larger issue with your conda installation that is leading to the issues you are seeing. From my understanding the glibc issue is a more nebulous error from conda. I have seen that before when trying to install ISIS and the error being glibc is basically conda saying "I don't know what went wrong". We will have to see where the internal discussion takes this problem and work from there regarding that problem with conda.

**Comment by islamomar97** [comment] 2023-11-16 23:59
I will try again and tell you what I find 👌🏻. Thanks and regards.


Thanks & Regards,



[Logo  Description automatically generated]Islam Omar

Research Assistant

Electrical & Computer Engineering

NMSU, Knox Hall #305

***@***.***

[A picture containing paper clip, tool  Description automatically generated](575) 805 – 9676

[Logo  Description automatically generated]<https://www.linkedin.com/in/islam-omar-a42560110/>Islam Omar<https://www.linkedin.com/in/islam-omar-a42560110/>



[X]



________________________________

**Comment by AustinSanders** [comment] 2023-11-17 00:20
@islamomar97 It may be worth running `conda clean --all` to ensure that you're getting a clean pull of the packages.

Oddly, I'm also seeing posts that indicate that updating conda has worked for some users.  Can you verify that your conda distribution is up to date?

**Comment by islamomar97** [comment] 2023-11-17 00:33
I will try that too next time, and yeah I was making sure that everything, including conda, is up to date.


Thanks & Regards,



[Logo  Description automatically generated]Islam Omar

Research Assistant

Electrical & Computer Engineering

NMSU, Knox Hall #305

***@***.***

[A picture containing paper clip, tool  Description automatically generated](575) 805 – 9676

[Logo  Description automatically generated]<https://www.linkedin.com/in/islam-omar-a42560110/>Islam Omar<https://www.linkedin.com/in/islam-omar-a42560110/>



[X]



________________________________

**Comment by antonhibl** [comment] 2024-04-06 01:42
@islamomar97 were you able to resolve this with the recommended solutions above? I am still not able to reproduce this myself so it seems like it may be an issue with your conda installation rather than something on ISIS' side.

**Comment by antonhibl** [comment] 2024-04-09 22:32
I am going to close this as it has not been reproduceable and seems to be an unrelated problem from something with conda. Please feel free to reopen the issue if the problem persists.

**Closed as completed by antonhibl** 2024-04-09 22:32 UTC
Labels: bug
