### ISSUE TITLE
The jigsaw bundleout.txt file needs to be cleaned up

### ISSUE THREAD

**Issue by twilson271828** [DOI-USGS/ISIS3#3227] opened 2019-04-15 22:27 UTC
**Description**  
At present, some columns of data do not have headers describing the column values, or unit descriptions such as km/s.

**Example**  
Currently:  
IMAGE MEASURES SUMMARY
==========================

input/Sub4-AS15-M-0583_msk.cub     131 of   131  1.478  2.742  2.202
input/Sub4-AS15-M-0584_msk.cub     205 of   205  1.323  1.241  1.282
input/Sub4-AS15-M-0585_msk.cub     219 of   219  1.055  1.250  1.156
input/Sub4-AS15-M-0586_msk.cub     229 of   229  1.350  1.354  1.352
input/Sub4-AS15-M-0587_msk.cub     166 of   166  1.026  1.168  1.099
input/Sub4-AS15-M-1423.cub       9 of     9  1.482  1.801  1.649
input/Sub4-AS15-M-1537.cub      10 of    10 14.959  8.857 12.293

With the change:

IMAGE MEASURES SUMMARY
==========================
           Image Name                                 Images      RMS1 RMS2 RMS3 
                                                                Accepted      
input/Sub4-AS15-M-0583_msk.cub     131 of   131  1.478  2.742  2.202
input/Sub4-AS15-M-0584_msk.cub     205 of   205  1.323  1.241  1.282
input/Sub4-AS15-M-0585_msk.cub     219 of   219  1.055  1.250  1.156
input/Sub4-AS15-M-0586_msk.cub     229 of   229  1.350  1.354  1.352
input/Sub4-AS15-M-0587_msk.cub     166 of   166  1.026  1.168  1.099
input/Sub4-AS15-M-1423.cub       9 of     9  1.482  1.801  1.649
input/Sub4-AS15-M-1537.cub      10 of    10 14.959  8.857 12.293

Stretch:  Find a way to output this file in a format which would allow it to be easily
imported into a pandas dataframe or into R so that advanced statistical analysis can be
performed on it.

**Comment by jlaura** [comment] 2019-08-16 19:08
I believe this was closed with #3404. Please reopen is I am incorrect. (:tada: to everyone that contributed code and reviews on this one)

**Comment by lwellerastro** [comment] 2019-08-19 20:32
I'm not seeing anything new in the bundleout.txt under 3.8.1.  Should I expect these changes under that version?

**Comment by acpaquette** [comment] 2019-08-19 21:00
@lwellerastro This did not make it into 3.8.1 and will be coming with 3.9. It's good that you're tracking and keeping us up to date if some change was made but you're not seeing it in the build you are expecting :+1:

**Comment by lwellerastro** [comment] 2019-08-19 21:09
Thanks @acpaquette.  I see it's not mentioned in the release notes and in one of the linked posts there's this "@jlaura @lwellerastro During today's stand up we decided to add the old function back and either flag it as deprecated or make it call the new functions. This way these changes can still go ourt in 3.9. @acpaquette and I will be working on this today."

That didn't apparently sink in at the time or I read right over it.  I just assumed that it got in because it got closed.  My bad.  Hard to keep track of everything.

**Comment by acpaquette** [comment] 2019-08-19 21:11
No problem, happy to clarify things.

**Comment by lwellerastro** [comment] 2019-08-28 17:47
I have had the opportunity to test the changes to bundleout.txt today on a small data set and it could use a little help.  There are a lot of extra space/tabs for the columns that had units added to the rows that they describe which makes it very hard to read.  

You will see quite clearly what I mean if you compare a before and after file.  Take a look at isis3.8.0_bundleout.txt and isis3.9.0-RC1_bundleout.txt under /work/users/lweller/Isis3Tests/Jigsaw/BundleOutUpdates/.  The changes are under the sections "IMAGE MEASURES SUMMARY" and "IMAGE EXTERIOR ORIENTATION".  I have not yet verified that the calculations for the Total RMS of the pixels on the images is correct.  I need to consult with a spreadsheet first.  I believe Ken verified the calculation though. (Confirmed - calculation's are good).

If this is data you care to experiment with everything you need is in that directory and the command is captured in proc.scr.

You might also compare the new output to the bundleout.txt that was shared with me when this post was originally worked on.  I thought I was looking at actual new output, but I think it may have been a mock up.  That file is attached and also under the directory mentioned above and has the same name as the attachement.
[apollo_bundleout.txt](https://github.com/USGS-Astrogeology/ISIS3/files/3552192/apollo_bundleout.txt)

**Comment by lwellerastro** [comment] 2019-09-16 17:06
This issue needs to be re-opened again (I can only comment for some reason) - sorry.  I think it might help if I tested it on "real" data before changes are committed or tests are made on at least something different or at least in addition to  that what it is being tested against because the changes seen to only accommodate the test data.

See isis3.9.0-RC2_bundleout.txt and isis3.9.0-RC2_fullpath_bundleout.txt under /work/users/lweller/Isis3Tests/Jigsaw/BundleOutUpdates/.  In the first case the files are in a local directory and the input list contains no path names.  The output under "Image Measures Summary" has the filenames right justified which is different than in the past, but that column and everything to the right are very readable.

In the second case the full path was included in the input image list.  The filenames under "Image Measures Summary" are left-justified (which makes more sense to me) and the columns to the right seem orderly enough, however, the column titles for Measures and RMS haven't moved, so the user still doesn't quite know what they are looking at.  Also, the Total RMS output values have not changed positions and they need to slide to the right along with the columns they are associated with.

The only word of advice I can provide here is the columns and their headings for the Image Measures Summary will be driven by the input image list and the number of characters included on any one line, and that may vary in an infinite number of ways.

**Comment by jlaura** [comment] 2019-09-18 17:12
See #3456

**Closed as completed** 2019-09-18 17:11 UTC
Labels: enhancement, in progress, Products
