### ISSUE TITLE
Output of "shadow" program drifts as DTM resolution changes.

### ISSUE THREAD

**Issue by rvwagner** [DOI-USGS/ISIS3#5035] opened 2022-08-18 02:48 UTC
**ISIS version(s) affected**: 3.10.2, 7.0

**Description**  
As you reduce the scale of the input DTM put into the shadow program, the position of features in the output drifts away from being aligned to the DTM. They even drift relative to null pixels copied in from the DTM, so it doesn't seem to be a simple misalignment of the input cubes.  

I suspect that the cause of this error is simply that the output of shadow, at least in south polar stereographic projection on the Moon, is always shifted 2 pixels up and to the left of the correct position, and this only becomes noticeable when comparing ~20m/px data to ~3m/px data at the same point.  This is based on the relative offsets between shadow-produced images of a NAC DTM reduced to various levels, and the orthophotos of that same DTM (I do not have a code example for doing that comparison, unfortunately).

![ShadowBugAnim](https://user-images.githubusercontent.com/9440209/185281195-a8188e1a-92f5-4d0a-93a4-bfbe62ef7d02.gif)

**How to reproduce**  
The attached files provide a base for the following code, which produces the files in the animation above.  It's a tiny clipping from a polar NAC DTM, converted to radius, and an arbitrary NAC image that overlaps it.

 for x in 1 2 3 4 5; do
  reduce from=dtm.cub to=t$x.cub lsc=$x ssc=$x;
  shadow from=t$x.cub match= M1146718551L.shift.cub to=s$x.cub;
 done
 qview t[1-5].cub s[1-5].cub

[shadow_error_demo.zip](https://github.com/USGS-Astrogeology/ISIS3/files/9367212/shadow_error_demo.zip)

**Comment by Kelvinrr** [comment] 2022-08-18 15:33
We can probably look into this as part in the coming days as part of the LROC work. Another possibility is the reduction app might be pulling the pixels towards the origin on the image, although like you said that by itself wouldn't explain the null pixels moving as well.

**Comment by rvwagner** [comment] 2022-08-18 17:14
I’m pretty sure it’s shadow that’s causing the issue. The reduced cubes (left panel of animation) show no sign of drifting, at least not by more than a fractional pixel. Also, I originally spotted this bug after using map2map to downsample the DTM, and got the same pattern of non-offset reduced DTM and significantly offset shadow image.

**Comment by Kelvinrr** [comment] 2022-08-18 22:50
I think to replicate this we need the shape model cube /ser/geodata/basemaps/MOON/Lunar_topography/LOLA/March2013/LDEM_75S_30M.demprep.cub that these were prepared with.

**Comment by rvwagner** [comment] 2022-08-18 22:55
Whoops.  That file's obnoxiously large, so how about just switching back to the built-in shapemodel?  The result of the above demo code stays the same after doing this:

`editlab grpn=Kernels keyw=Shapemodel value='$base/dems/ldem_128ppd_Mar2011_clon180_radius_pad.cub' from=M1146718551L.shift.cub`

**Comment by Kelvinrr** [comment] 2022-08-23 22:51
Looks like the gist of the issue is has to do with `Hillshade`'s buffer at the edge of the image going off the image and becoming `null`s which create a final pixel value of LRS. The buffer is also shifted by +1 in both the line/sample direction. Im like half way through finding a good solution as the buffer object is passed though 3 different classes.

**Comment by Kelvinrr** [comment] 2022-08-31 01:43
![shadow](https://user-images.githubusercontent.com/13245976/187574108-af6d1159-f8fe-4b34-a76b-69b7a90ce2c2.gif)

I think I got it, the window for computing the shadow was shifted over one pixel from the center of the DN. Then inside the window the origin was shifted one pixel.  I can get a PR up in a bit.

**Comment by Kelvinrr** [comment] 2022-08-31 01:44
I think I got it, the window for computing the DN was shifted one pixel. Inside that window, the origin was further shifted one pixel. 

![shadow](https://user-images.githubusercontent.com/13245976/187575421-03dfc4c0-4891-49f1-8fc1-52bc7e498ea5.gif)

**Comment by Kelvinrr** [comment] 2022-09-19 15:48
Fixed with #5047

**Closed as completed by Kelvinrr** 2022-09-19 15:48 UTC
Labels: bug
