### ISSUE TITLE
updating ISIS, no support for ISIS4+ on Mac 10.14?, mimap2isis

### ISSUE THREAD

**Issue by geokramer** [DOI-USGS/ISIS3#4476] opened 2021-05-19 15:27 UTC
I apologize in advance for probably posting to the wrong category and likely not following appropriate Github and developer protocols when trying to ask questions and resolve issues. In my defense, I am paid to analyze planetary mission data and make maps, and I have - quite literally - already spent more than half of my grant's funds trying to figure out: 1) how to make mimap2isis work, 2) learn it doesn't, 3) find this: https://github.com/USGS-Astrogeology/ISIS3/pull/4432?_pjax=%23js-repo-pjax-container from which I think I need to update ISIS to 5?, 4) try to update ISIS only to learn that apparently I can't because I run Mac OS 10.14?

I had put myself through the several hours of learning how to install and update ISIS before it moved to Github. I am having a very hard time navigating - what looks to me like - the ISIS3 Github labyrinth. I am lost. Please can someone help in something close to "real time"?

*I hope this write up does not read rude or accusatory. That is not my intention. I am not privy to the subtleties of tone in writing, especially my own writing, and have been told that my writing can come off in an unintended tone. I am frustrated with my own ignorance and am genuinely asking for help. 
Thank you.

**Comment by jessemapel** [comment] 2021-05-19 15:35
#4432 is not yet merged, so it's not available in any public release. It will become available in the 5.1 release coming up in July.

We cannot provide hands on installation support, but we are happy to help as much as we can asynchronously. Can you be more specific about where you are encountering issues in the installation process. Going step-by-step through the installation instructions in the README indicate where you are encountering errors and what they are. All of the Mac developers and our CI builds run on Mac 10.14 without issue.

**Comment by geokramer** [comment] 2021-05-19 16:39
I installed ISIS3 on this machine (I think) 2 years ago. I know I even successfully updated it some months ago. Now updatiung is not working for me.

Here's my attempts (If pasting this as "code" was the wrong thing to do, please tell me):

```
(base) Georgianas-MacBook-Pro:Schrodinger-USGSmap gkramer$ conda update isis

PackageNotInstalledError: Package is not installed in prefix.
  prefix: //miniconda3
  package name: isis


(base) Georgianas-MacBook-Pro:Schrodinger-USGSmap gkramer$ conda update isis3

PackageNotInstalledError: Package is not installed in prefix.
  prefix: //miniconda3
  package name: isis3
```
After scouring ISIS3 github I found a thread (I apologize if I am misusing terminology) about trying `conda install -c usgs-astrogeology isis=4.3.0` (I can't find the thread again to reference here, sorry). So I tried and this happened:

```
(base) Georgianas-MacBook-Pro:Schrodinger-USGSmap gkramer$ conda install -c usgs-astrogeology isis=4.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.14.6=0
  - feature:|@/osx-64::__osx==10.14.6=0
  - isis=4.3.0 -> pcl -> __osx[version='>=10.12']

Your installed version is: 10.14.6
```
Hence why I think 10.14 is unsupported?
Maybe I need to do a fresh install? Although I don't even know how to properly delete everything.
These are my failed attempts to update. Is this enough to help me?

Thank you.

**Comment by jessemapel** [comment] 2021-05-19 16:45
Are you installing into an environment or into your base Anaconda installation? Can you run `conda info` and post the results of that?

**Comment by geokramer** [comment] 2021-05-19 18:06
```
(base) Georgianas-MacBook-Pro:~ gkramer$ conda info

     active environment : base
    active env location : //miniconda3
            shell level : 1
       user config file : /Users/gkramer/.condarc
 populated config files : /Users/gkramer/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : //miniconda3  (writable)
      conda av data dir : //miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : //miniconda3/pkgs
                          /Users/gkramer/.conda/pkgs
       envs directories : //miniconda3/envs
                          /Users/gkramer/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by astrostu** [comment] 2021-05-19 18:27
I'm certainly no expert in this, but I have had no issues running any ISIS version since 3.6 (thru 4.4) on macOS 10.13.x thru 10.15.x and 11.0.x on both Intel and Apple CPUs via the conda install; I've had no issues with previous versions of ISIS running on macOS 10.5-ish through 10.13.  I've not used miniconda before, my understanding is that it is a bare-bones Anaconda installation without any of the normal packages.  Perhaps you can try uninstalling it, installing "regular" conda, and install ISIS?

[The second answer (not the first that's checked) looks like the proper way to uninstall.](https://stackoverflow.com/questions/29596350/how-to-uninstall-mini-conda-python)

Then, after installing Anaconda, follow the instructions starting at step 5 [here](https://github.com/USGS-Astrogeology/ISIS3).  So, from the (base) conda environment, you create a new ISIS conda environment, activate it, and install ISIS.

The uninstall-reinstall suggestion is basically the "giggle the cord" of suggestions, but sometimes giggling the cord does work.

**Comment by jessemapel** [comment] 2021-05-20 13:52
@geokramer You may be running into issues with your Python version as you are installing into your base which is python 3.7. Try the following:

```
conda create -n isis python=3.6
```

this will ask if you want to make an environment in `/miniconda3/envs/isis` enter `y` for yes. Then run:

```
conda activate isis
conda config --env --add channels conda-forge
conda config --env --add channels usgs-astrogeology
```

This will set you up with an environment, so an isolated install, that is properly configured to install ISIS.

**Comment by jessemapel** [comment] 2021-05-20 13:53
Potentially related to #3885

**Comment by geokramer** [comment] 2021-05-23 23:22
@jessemapel That did not solve the updating problem. What it did do is create another isis directory and subdirectories. So now in addition to `/miniconda3/envs/isis3` I have `/miniconda3/envs/isis`.
Neither `conda update isis` nor `conda update isis3` works - they both give me the same error as before.

Should I follow the advice of @astrostu and try to uninstall everything? Do I need full anaconda? I'd rather not if I don't need it.

**Comment by jessemapel** [comment] 2021-05-24 14:08
@geokramer From your `conda info` command you do not have your environment activated. Are you running `conda activate` with either `isis` or `isis3` prior to `conda install`?

**Comment by geokramer** [comment] 2021-05-24 17:11
Same problem:
```
(isis) Georgianas-MacBook-Pro:/ gkramer$ conda info

     active environment : isis
    active env location : //miniconda3/envs/isis
            shell level : 2
       user config file : /Users/gkramer/.condarc
 populated config files : /Users/gkramer/.condarc
                          //miniconda3/envs/isis/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : //miniconda3  (writable)
      conda av data dir : //miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/usgs-astrogeology/osx-64
                          https://conda.anaconda.org/usgs-astrogeology/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : //miniconda3/pkgs
                          /Users/gkramer/.conda/pkgs
       envs directories : //miniconda3/envs
                          /Users/gkramer/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

(isis) Georgianas-MacBook-Pro:/ gkramer$ conda update isis

PackageNotInstalledError: Package is not installed in prefix.
  prefix: //miniconda3/envs/isis
  package name: isis
```

**Comment by jessemapel** [comment] 2021-05-24 17:28
That still lists your python version as 3.7 for the isis environment. Can you run `conda list` with the isis environment active and share the output of that?

**Comment by geokramer** [comment] 2021-05-24 17:40
```
(isis) Georgianas-MacBook-Pro:/ gkramer$ conda list
# packages in environment at //miniconda3/envs/isis:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py36h79c6626_1    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
python                    3.6.13          h7728216_0_cpython    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                49.6.0           py36h79c6626_3    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
(isis) Georgianas-MacBook-Pro:/ gkramer$ 

```

**Comment by jessemapel** [comment] 2021-05-24 17:47
Okay, let's try using mamba instead of conda to install. Go ahead and install mamba into your environment with `conda install -c conda-forge mamba`. Then retry the installation of ISIS with `mamba install -c usgs-astrogeology isis`.

**Comment by geokramer** [comment] 2021-05-24 17:50
ok, but first can we uninstall the current installation(s)? Or do that after?

**Comment by jessemapel** [comment] 2021-05-24 17:51
You have just made the environment, there is nothing installed into it yet.

**Comment by geokramer** [comment] 2021-05-24 18:12
ok.
To be clear, I should be in the isis environment, right?

**Comment by jessemapel** [comment] 2021-05-24 18:14
Yes, we're going to install into the isis environment, so make sure it is active prior to running the commands from the previous post.

**Comment by geokramer** [comment] 2021-05-24 18:22
Here is what happened following your instructions above (and answering "y" when prompted):

`
(base) Georgianas-MacBook-Pro:~ gkramer$ isis
(isis3) Georgianas-MacBook-Pro:~ gkramer$ conda install -c conda-forge mamba
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: //miniconda3/envs/isis3

  added / updated specs:
    - mamba


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asn1crypto-1.4.0           |     pyh9f0ad1d_0          78 KB  conda-forge
    brotlipy-0.7.0             |py36h20b66c6_1001         357 KB  conda-forge
    cffi-1.14.5                |   py36hfaecaff_0         217 KB  conda-forge
    chardet-4.0.0              |   py36h79c6626_1         219 KB  conda-forge
    conda-4.10.1               |   py36h79c6626_0         3.1 MB  conda-forge
    conda-package-handling-1.7.3|   py36hfa26744_0         1.5 MB  conda-forge
    cryptography-2.2.1         |           py36_0         416 KB  conda-forge
    libsolv-0.7.18             |       hcf210ce_0         390 KB  conda-forge
    mamba-0.1.2                |   py36h863e41a_0         101 KB  conda-forge
    pycosat-0.6.3              |py36h20b66c6_1006         113 KB  conda-forge
    pyopenssl-19.0.0           |           py36_0          81 KB  conda-forge
    pysocks-1.7.1              |   py36h79c6626_3          27 KB  conda-forge
    ruamel_yaml-0.15.80        |py36h49ba835_1004         240 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.8 MB

The following NEW packages will be INSTALLED:

  asn1crypto         conda-forge/noarch::asn1crypto-1.4.0-pyh9f0ad1d_0
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py36h20b66c6_1001
  cffi               conda-forge/osx-64::cffi-1.14.5-py36hfaecaff_0
  chardet            conda-forge/osx-64::chardet-4.0.0-py36h79c6626_1
  conda              conda-forge/osx-64::conda-4.10.1-py36h79c6626_0
  conda-package-han~ conda-forge/osx-64::conda-package-handling-1.7.3-py36hfa26744_0
  cryptography       conda-forge/osx-64::cryptography-2.2.1-py36_0
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  libsolv            conda-forge/osx-64::libsolv-0.7.18-hcf210ce_0
  mamba              conda-forge/osx-64::mamba-0.1.2-py36h863e41a_0
  pycosat            conda-forge/osx-64::pycosat-0.6.3-py36h20b66c6_1006
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/osx-64::pyopenssl-19.0.0-py36_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py36h79c6626_3
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  ruamel_yaml        conda-forge/osx-64::ruamel_yaml-0.15.80-py36h49ba835_1004
  tqdm               conda-forge/noarch::tqdm-4.60.0-pyhd8ed1ab_0
  urllib3            conda-forge/noarch::urllib3-1.26.4-pyhd8ed1ab_0
  yaml               conda-forge/osx-64::yaml-0.2.5-haf1e3a3_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
pyopenssl-19.0.0     | 81 KB     | ##################################### | 100% 
brotlipy-0.7.0       | 357 KB    | ##################################### | 100% 
conda-4.10.1         | 3.1 MB    | ##################################### | 100% 
libsolv-0.7.18       | 390 KB    | ##################################### | 100% 
asn1crypto-1.4.0     | 78 KB     | ##################################### | 100% 
pycosat-0.6.3        | 113 KB    | ##################################### | 100% 
cffi-1.14.5          | 217 KB    | ##################################### | 100% 
pysocks-1.7.1        | 27 KB     | ##################################### | 100% 
ruamel_yaml-0.15.80  | 240 KB    | ##################################### | 100% 
conda-package-handli | 1.5 MB    | ##################################### | 100% 
mamba-0.1.2          | 101 KB    | ##################################### | 100% 
chardet-4.0.0        | 219 KB    | ##################################### | 100% 
cryptography-2.2.1   | 416 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(isis3) Georgianas-MacBook-Pro:~ gkramer$ mamba install -c usgs-astrogeology isis

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Getting  usgs-astrogeology osx-64
Getting  usgs-astrogeology noarch
Getting  conda-forge osx-64
Getting  conda-forge noarch
Getting  pkgs/main osx-64
Getting  pkgs/main noarch
Getting  pkgs/r osx-64
Getting  pkgs/r noarch

Looking for: ['isis', 'python 3.6.0']

218 packages in https://conda.anaconda.org/usgs-astrogeology/osx-64
0 packages in https://conda.anaconda.org/usgs-astrogeology/noarch
173497 packages in https://conda.anaconda.org/conda-forge/osx-64
56010 packages in https://conda.anaconda.org/conda-forge/noarch
21196 packages in https://repo.anaconda.com/pkgs/main/osx-64
3529 packages in https://repo.anaconda.com/pkgs/main/noarch
5314 packages in https://repo.anaconda.com/pkgs/r/osx-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch

## Package Plan ##

  environment location: //miniconda3/envs/isis3

  added / updated specs:
    - isis
    - python==3.6.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-1.67.0               |           py36_4          11 KB
    isis-3.10.2                |           py36_0        12.6 MB  usgs-astrogeology
    libboost-1.67.0            |       hebc422b_4        12.7 MB
    opencv-3.2.0               |np113py36_blas_openblas_204        18.7 MB  conda-forge
    py-boost-1.67.0            |   py36h6440ff4_4         288 KB
    ------------------------------------------------------------
                                           Total:        44.3 MB

The following NEW packages will be INSTALLED:

  boost              pkgs/main/osx-64::boost-1.67.0-py36_4
  isis               usgs-astrogeology/osx-64::isis-3.10.2-py36_0
  libboost           pkgs/main/osx-64::libboost-1.67.0-hebc422b_4
  py-boost           pkgs/main/osx-64::py-boost-1.67.0-py36h6440ff4_4

The following packages will be DOWNGRADED:

  opencv                       3.3.0-py36_blas_openblas_200 --> 3.2.0-np113py36_blas_openblas_204


Proceed ([y]/n)? y


Downloading and Extracting Packages
isis-3.10.2          | 12.6 MB   | ##################################### | 100% 
libboost-1.67.0      | 12.7 MB   | ##################################### | 100% 
boost-1.67.0         | 11 KB     | ##################################### | 100% 
opencv-3.2.0         | 18.7 MB   | ##################################### | 100% 
py-boost-1.67.0      | 288 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(isis3) Georgianas-MacBook-Pro:~ gkramer$ 
`

**Comment by jessemapel** [comment] 2021-05-24 18:25
It looks like it properly downloaded, but it installed 3.10. Run this now: `mamba install -c usgs-astrogeology isis=5.0`.

**Comment by geokramer** [comment] 2021-05-24 18:26
Problem encountered:
`Problem: package isis-5.0.0-0 requires armadillo >=9.200,<10.0a0, but none of the providers can be installed
`

**Comment by jessemapel** [comment] 2021-05-24 18:36
Try running `mamba install -c conda-forge armadillo=9.200.7` and post the output

**Comment by geokramer** [comment] 2021-05-24 18:40
```
(isis3) Georgianas-MacBook-Pro:~ gkramer$ mamba install -c conda-forge armadillo=9.200.7

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Getting  conda-forge osx-64
Getting  conda-forge noarch
Getting  pkgs/main osx-64
Getting  pkgs/main noarch
Getting  pkgs/r osx-64
Getting  pkgs/r noarch
Getting  usgs-astrogeology osx-64
Getting  usgs-astrogeology noarch

Looking for: ['armadillo 9.200.7.*', 'python 3.6.0']

173497 packages in https://conda.anaconda.org/conda-forge/osx-64
56045 packages in https://conda.anaconda.org/conda-forge/noarch
21196 packages in https://repo.anaconda.com/pkgs/main/osx-64
3529 packages in https://repo.anaconda.com/pkgs/main/noarch
5314 packages in https://repo.anaconda.com/pkgs/r/osx-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch
218 packages in https://conda.anaconda.org/usgs-astrogeology/osx-64
0 packages in https://conda.anaconda.org/usgs-astrogeology/noarch
Encountered problems while solving.
Problem: package isis3-3.9.1-py36_0 requires armadillo 8.200.0, but none of the providers can be installed

```

**Comment by geokramer** [comment] 2021-05-24 20:03
This has definitely broken isis on my system.

**Comment by jessemapel** [comment] 2021-05-24 20:12
> This has definitely broken isis on my system.

You need to be more specific than this. I'm currently working on reproducing the Armadillo error and trying to figure out why it's happening.

**Comment by geokramer** [comment] 2021-05-24 20:59
I'm sorry.
It seems I cannot run ISIS programs since doing these. I'm just letting you know. Here's an example:

```
(isis3) Georgianas-MacBook-Pro:/ gkramer$ isis2std
dyld: Library not loaded: @rpath/libopenblas.0.dylib
  Referenced from: //miniconda3/envs/isis3/bin/isis2std
  Reason: no suitable image found.  Did find:
	//miniconda3/envs/isis3/lib/libBulletDynamics.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libBulletCollision.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libLinearMath.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_atomic.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_log.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_regex.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_log_setup.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_serialization.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_chrono.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_math_c99.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_signals.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_container.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_math_c99f.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_context.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_math_c99l.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_system.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_math_tr1.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_math_tr1f.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_math_tr1l.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_test_exec_monitor.a/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_date_time.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_thread.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_exception.a/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_timer.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_filesystem.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_prg_exec_monitor.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_program_options.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_unit_test_framework.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_iostreams.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_wave.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libboost_random.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libgsl.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libhdf5.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libc++.dylib/libopenblas.0.dylib: stat() failed with errno=20
	/usr/lib/libpthread.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libz.dylib/libopenblas.0.dylib: stat() failed with errno=20
	/usr/lib/libdl.dylib/libopenblas.0.dylib: stat() failed with errno=20
	//miniconda3/envs/isis3/lib/libpng.dylib/libopenblas.0.dylib: stat() failed with errno=20
Abort trap: 6

```

**Comment by jessemapel** [comment] 2021-05-24 21:08
> Problem: package isis3-3.9.1-py36_0 requires armadillo 8.200.0, but none of the providers can be installed

It looks like this is the problem. Similarly, the rpath error above appears to be looking for dependencies across your environments. Do you have the **isis3** package installed in your base environment? You cannot install the **isis3** and **isis** packages into the same or nested environments (all environments are nested under base) because conda thinks they are completely different.

If you want to fix your isis3.9 install, then delete the isis environment with `conda remove -n isis --all` and in your isis3 environment install the proper version of openBLAS with `conda install -c conda-forge openblas=0.2.19=2`.

**Comment by astrostu** [comment] 2021-05-24 21:17
@jessemapel That's why I suggested wiping and doing a clean install.  You might recall I had a similar library dependency issue when I tried doing various things in a Linux virtual environment.  It was fixed when doing a clean wipe/install.

@geokramer In case you don't know, when you install something via conda, ideally the program tells conda everything that it needs to run, AND the exact version of all those libraries.  If it misses something, or you install something on top of that that changes a library version, or if you had a previous version of that library installed and the new program doesn't do a version check, everything can break.  That might be part of the issue above?  I'd trust @jessemapel more than me, though.

**Comment by jessemapel** [comment] 2021-05-24 21:18
I was able to do a fresh install of ISIS 5.0.0 on OSX 10.14.6 with a fresh Miniconda install.

I would recommend a fresh Miniconda install at this point. You can leave your old install as is and just comment out the initialization in your start-up files in case you want to revert.

**Comment by geokramer** [comment] 2021-05-25 17:29
I had originally installed ISIS per the instructions on the ISIS Github site. I don't know why the python 3.6/3.7 issue. Probably I installed 3.7 sometime soon after.

Since ISIS seems to not be working now I would prefer having everything neat and tidy on my machine (it's a laptop, I don't have room for unnecessary stuff, also it bothers my not-actually-but-kind-of-like OCD.

@jessemapel Do you suggest following the instructions for wiping conda and everything associated with it (which would only be ISIS) in the link @astrostu provided? What about mamba? Or is that inherent in my system? Really, aside from a few linux/unix commands, you're working with a very tech ignorant person. I appreciate you holding my hand.

**Comment by jessemapel** [comment] 2021-05-25 17:44
Follow the instructions that @astrostu linked for uninstalling miniconda. We haven't made any changes to anything outside of your miniconda install. This is actually one of the main reasons we use Anaconda is that it isolates everything so that it's easy to separate things and clean up things.

**Comment by geokramer** [comment] 2021-05-25 18:01
@jessemapel While cleaning up my .bash_profile I noticed that it began:
```
# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH
```
This was followed by what miniconda added. This beginning is the extent of the original (backup) and to what I have now reverted). This was probably the culprit, wasn't it? If so, please advise as to what I should replace it with?

**Comment by jessemapel** [comment] 2021-05-25 18:07
This is likely the culprit. I'm not sure why it was there or what you should change it to. I would recommend just commenting it out. Anaconda manages your PATH for you and can have trouble when you also modify your PATH.

**Comment by geokramer** [comment] 2021-05-25 18:33
Thank you @jessemapel and @astrostu for your help. I am going to start the re-install.

**Comment by AustinSanders** [comment] 2021-08-05 19:09
I'm closing this issue, as it seems to be resolved.  Feel free to reopen the issue if any additional information becomes available.

**Closed as completed by AustinSanders** 2021-08-05 19:09 UTC
Labels: question, installation
