### ISSUE TITLE
Jigsaw - spice rotation fit error when solving for accelerations for HRSC data

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5023] opened 2022-08-04 19:36 UTC
**ISIS version(s) affected**: 7.0.0

**Description**  
Jigsaw fails with the following error when attempting to solve for camera accelerations for a global Phobos HRSC dataset:

  Group = Error
    Program = jigsaw
    Class   = "PROGRAMMER ERROR"
    Code    = 3
    Message = "Unable to evaluate the derivative of the SPICE rotation fit
               polynomial for the given coefficient index [2]. Index is
               negative or exceeds degree of polynomial [1]"
    File    = SpiceRotation.cpp
    Line    = 2152
  End_Group

I can solve for angles without error.

**How to reproduce**  
An image list and network are available under my work users in Isis3Tests/Jigsaw/Phobos/.  The images are on scratch but can be made local if necessary.  Please let me know.

Jigsaw command:

`jigsaw froml=Phobos_HRSC_FFCombine_Del_4.lis cnet=Phobos_HRSC_FFCombine_SubReg_Ground_3.net onet=JigOut_RadAccelTwist_Phobos_HRSC_FFCombine_SubReg_Ground_3.net radius=yes update=no sigma0=1.0e-5 maxits=20 camsolve=accelerations twist=yes overexisting=yes spsolve=position overhermite=yes camera_angles_sigma=1.5 camera_angular_velocity_sigma=0.75 camera_angular_acceleration_sigma=0.3 spacecraft_position_sigma=1000 point_radius_sigma=500 file_prefix=RadAccelTwist_Ground_3`

I have also tried to solve by setting overexisting and overhermite= false but get the same error.

**Additional context**  
A small set of test data (~40 images) from earlier this year can solve for camera accelerations successfully.  I can point you to that if useful.

**Comment by lwellerastro** [comment] 2023-02-01 17:13
this is still a problem

**Comment by AustinSanders** [comment] 2023-03-02 17:41
It looks like there are 4 images in the network for which the InstrumentPosition table only has 2 entries, and there's a block of logic in jigsaw/bundleadjust that sets degree == 1 for a table with 2 entries.  The weird thing is that all of this seems to be "correct" with respect to processing, so we're following the correct set of steps, but we're still arriving at results we don't want.

Whether it's good or bad news, it looks like those 4 images are the cause of the failure in jigsaw.  It's not clear what's different about those images that'a making the tables smaller than the rest.  In general, the images have an InstrumentPosition table with 3-6 entries.

Since everything is "technically correct," there's not really anything that we can modify that wouldn't have negative impacts elsewhere, but there are two additive changes that might resolve the issue.  First, we could try adding flags to spiceinit that would stop ISIS from minimizing the tables, something like --no-reduce coupled with a tablename.  This might result in a larger .cub, and I'm not sure how it would affect processing times.

Another option is to have a flag in jigsaw that allows it to throw out problematic data and log any images that were excluded.

For reference, these are the images/tables that I think are causing the issue:
`
tabledump from=HG751_0000_BL2.clean.photr.cub name=InstrumentPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET-2416.4619015198,615.2867873512,-1642.6972812552,1.7645131887515,0.67070174419125,-2.1718990449693,543598628.44577-2395.3727349627,623.30461557826,-1668.641376041,1.7652347320624,0.6712844547862,-2.1704203805288,543598640.39514
tabledump from=HG751_0000_GR2.clean.photr.cub name=InstrumentPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET-2313.2772484067,654.54554103794,-1769.3678088505,1.7680389415812,0.67326094503515,-2.1646852317363,543598686.86494-2292.1460178846,662.59340539765,-1795.2255261805,1.768748231874,0.67375108234553,-2.1631772784296,543598698.81431
tabledump from=HG751_0000_IR2.clean.photr.cub name=InstrumentPosition
J2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET-2119.2573722247,728.50267705397,-2005.7209951342,1.7745124528588,0.67684257712563,-2.1507631473734,543598796.40091-2292.1460178846,662.59340539765,-1795.2255261805,1.768748231874,0.67375108234553,-2.1631772784296,543598698.81431
tabledump from=HG751_0000_IR2.clean.photr.cub name=InstrumentPositionJ2000X,J2000Y,J2000Z,J2000XV,J2000YV,J2000ZV,ET-2119.2573722247,728.50267705397,-2005.7209951342,1.7745124528588,0.67684257712563,-2.1507631473734,543598796.40091-2098.0488909154,736.59228945118,-2031.4120111992,1.7752029466446,0.67715300663584,-2.1491992628299,543598808.35028
`

Are either of these options viable solutions as a user?  If not, what are our other options?

**Comment by lwellerastro** [comment] 2023-03-02 18:14
Hi @AustinSanders, I can't say that I completely understand the problem or the spiceinit solution.  Someone more knowledge than me in regard to spice would have to make the call on adding to spiceinit. 

Having jigsaw identify and remove images from an iteration would be a great add to jigsaw and something we have wanted for a long time.  I think that is going to be a bit of work.  Having jigsaw die as it already and reporting more useful information to the user like the images it's failing on would be extremely useful.  But what is involved with that?

One other thing, the test set of data is a fraction of the actual network images I am working with, so how could I identify the above problem in the other 1000+ images I am working with for the HRSC network?  I am also working with MEX SRC images of the same target (Phobos) which also can not solve for accelerations, so clearly that network has images with a similar problem.

Which is making me think this is maybe less of a jigsaw issue and more of a spice/kernel issue or something.  With so little time left in this sprint, and this being potentially a somewhat different problem, I guess we need to understand what it would take to get jigsaw to provide a more meaningful error message and if that's something we want to address; and how can I identify problem images because I don't think I understand that problem enough to know what to look for in the data after spiceinit.  Is there something in the labels or do I need to run tabledump on the images and evaluate the results?  In looking at your output above, I couldn't tell what was wrong with it.

In the meantime, I will remove those 4 images from the test network and see if jigsaw runs as expected.

**Comment by lwellerastro** [comment] 2023-03-02 20:44
With @AustinSanders help I was able to identify 10 HRSC image in the network having CacheType=Linear (not HermiteSpline) under the InstrumentPosition  Table.  I removed those images from the network and I jigsaw now runs when camsolve=accelerations. Thankfully those images were not needed (very low res).

Unfortunately my MEX SRC network of Phobos has >2000 images and every single one has CacheType=Linear and camera accelerations can not be solved for those, or if/when they are tied to the HRSC and the two share a single network.
Update: Although I had been informed SRC is a line scan camera, its implementation in isis is as a framer. I don't know the correct answer but will assume the isis implementation is correct and not try to solve for camera accelerations for those images any longer.

From offline conversations that Austin will have to summarize better then me, it appear the ALE driver is overly reducing the spice information for these images such that important, necessary information is being omitted in order for jigsaw to run in the way the data need. I believe that topic will result in a new different git issue.

Likely related to https://github.com/USGS-Astrogeology/ISIS3/issues/3928

**Comment by AustinSanders** [comment] 2023-03-02 23:13
To provide additional context regarding the cache:

In order to correctly solve for acceleration using jigsaw, the table / cache must contain 3 or more records. Based on discussion that we found in [#3928](https://github.com/USGS-Astrogeology/ISIS3/issues/3928), ale creates caches that are significantly smaller than those created by ISIS.  It appears that, in some cases, ALE may in fact be over-minimizing the cache and abstracting away information that is necessary to solve for accelerations.   We may be able to adjust this behavior by configuring the tolerance in [ALE States::minimizeCache](https://github.com/USGS-Astrogeology/ale/blob/main/include/ale/States.h#L126).  Alternatively, since adjusting the tolerance doesn't guarantee that we won't over-minimize the cache, it might make sense to come up with a way to specify a minimum cache size.

**Comment by AustinSanders** [comment] 2023-03-03 21:17
A little more context:

I disabled the HRSC driver and reran spiceinit, and it resulted in an InstrumentPosition table with 3 records and CacheType=HermiteSpline, which is exactly what we want in this case.  This seems to indicate that the issue is with how ALE (or ISIS's interaction with ALE) is producing/minimizing the cache.

**Comment by AustinSanders** [comment] 2023-04-05 20:25
Closing in favor of https://github.com/DOI-USGS/ale/issues/525

**Closed as completed by AustinSanders** 2023-04-05 20:25 UTC
Labels: bug, Products
