### ISSUE TITLE
 Spice fail on version 4 #5005 

### ISSUE THREAD

**Issue by ndhverma** [DOI-USGS/ISIS3#5008] opened 2022-07-18 20:14 UTC
Hi,

ISIS 4.4.0 version fail on web server for spice

I am processing the MiniRF data set id: lsz_03737_1cd_xku_88s276_v1_cub.cub

ERROR The SPICE server returned incompatible SPICE data.
ERROR Unable to find PVL group [Plugins].

Kindly suggest how I can correct this error.

I have first convert the Mini-RF data into cub using mr2isis command.
Then run the web spice command

![image](https://user-images.githubusercontent.com/43364419/179608985-639bfa76-7509-42f0-9ee3-9f39e3a0f872.png)
after run the above command, following error I am getting
ERROR The SPICE server returned incompatible SPICE data.
ERROR Unable to find PVL group [Plugins].

**Comment by jessemapel** [comment] 2022-07-18 20:18
Hi, I'm marking this as a duplicate of #5005 

If you have more information or new information for that issue please add it over there instead of making a new issue.

**Closed as completed by jessemapel** 2022-07-18 20:18 UTC
Labels: bug, duplicate
