### ISSUE TITLE
spiceinit problem with user DEM if using web kernels 

### ISSUE THREAD

**Issue by Ben-Bussey** [DOI-USGS/ISIS3#4034] opened 2020-09-24 19:23 UTC
**ISIS version(s) affected**: 4.1.2

**Description**  
I get a smear model error if I try and use a local DEM.  I can run spiceinit on a LROC WAC cube (output from lrowac2isis) with web=yes for the SPICE.  But if I choose SHAPE=USER and point to a local DEM I get an error (attached) about initializing a camera model.  The DEM I am using has been through DEMPREP.

As a test I went and selected the DEM that is installed in the base/dem directory, which is the one that spiceinit uses if you leave shape=system. I get the same error

**How to reproduce**  
process a WAC CDR through lrowac2isis, to get an odd and even cube.  then try and run that cube through spiceinit using web=yes for the spice, and a local dem
![Screen Shot 2020-09-24 at 3 19 46 PM](https://user-images.githubusercontent.com/71727412/94190218-d10cdb00-fe79-11ea-9682-37fb08318a2e.png)

**Possible Solution**  

**Additional context**

**Comment by jessemapel** [comment] 2020-09-24 20:04
This is an unfortunate side effect of how the spice web server works. It basically runs spiceinit with your image label on our server that has the data area. So, anything that uses a local path for your system will not work with the spice web server.

For Surface models, there is potential to make this work. See #1986

**Comment by jessemapel** [comment] 2020-09-24 20:06
I'm going to leave this open for adding a better error message because it's easy to check for this case.

**Comment by jlaura** [comment] 2020-09-24 22:18
@kberryUSGS I believe that working on making this work with the SPICE server is out of scope for the calibration routines. Does it make sense to label this as a SPICE server related issue as we transition (longer term) to fully supporting remote SPICE?

**Comment by jlaura** [comment] 2020-09-28 15:44
It looks like this should have been fixed already via #3791. We need to redeploy those changes for the SPICE server. Thanks @Kelvinrr for identifying that merged PR for me!

**Comment by Kelvinrr** [comment] 2020-09-30 16:19
@jlaura that PR addresses the version issue (this seems more like a duplicate of https://github.com/USGS-Astrogeology/ISIS3/issues/1986, not https://github.com/USGS-Astrogeology/ISIS3/issues/3725), so I don't think that PR affects this problem at all (oddly enough, before the fix was deployed I'm surprised he got to the camera model init step using 4.x.x 🤔 ).

**Comment by jessemapel** [comment] 2020-12-15 17:10
After more discussion we're going to close this in favor of #1986. Basically the amount of work required to add an exception is low, but the amount of work to make this just work isn't that much more.

**Closed as completed** 2020-12-15 17:10 UTC
Labels: documentation
