### ISSUE TITLE
Jigsaw based kernels for LRO NAC images do not produce expected results

### ISSUE THREAD

**Issue by lwellerastro** [DOI-USGS/ISIS3#5178] opened 2023-04-08 00:07 UTC
**ISIS version(s) affected**: 7.1.0

**Description**  
Kernels created for jigsaw updated LRO NAC images do not produce the same geometry when applied to newly ingested images. Kernels were created for 18,000+ images (broken up by eye and year) when the problem was found while validating the new kernels before sending to interested colleagues. I boiled the problem down to one image and could reproduce the issue. The problem occurs for a jigsaw updated image and not a spiced image that went through a similar test.  The kernels based on a spiced file work as expected.

**How to reproduce**  
See data under my work directory at Isis3Tests/Kernels/LRONAC/.  The file proc.scr has the details.  A summary is below.  I'm sorry my names are heinous.  

The shape model is not local as indicated below.  See proc.scr for details on actual DEM location and ingestion information for the test file M110860982LE_ingest.cub. 

```
ckwriter from=M110860982LE_jigsawed.cub to=M110860982LE_jigsawed_ck.bc summary=summary_M110860982LE_jigsawed_ck.txt
spkwriter from=M110860982LE_jigsawed.cub to=M110860982LE_jigsawed_spk.bsp summary=summary_M110860982LE_jigsawed_spk.txt

cp M110860982LE_ingest.cub jigsawkernelbased_M110860982LE.cub

spiceinit from=jigsawkernelbased_M110860982LE.cub shape=user model=LRO_LOLA_SPole75S_LDEM_30m_mar2014_radius.cub spksmithed=true extra="(M110860982LE_jigsawed_ck.bc,M110860982LE_jigsawed_spk.bsp)"

campt from=M110860982LE_jigsawed.cub to=camout_M110860982LE_jigsawed.pvl
campt from=jigsawkernelbased_M110860982LE.cub to=camout_jigsawkernelbased_M110860982LE.pvl
 
meld camout_M110860982LE_jigsawed.pvl camout_jigsawkernelbased_M110860982LE.pvl

```

**Additional context**  
The jigsaw updated images were ingested from pds edrs under isis7.1.0 in March and updated by jigsaw about 2 weeks ago.  Everything is current. Jigsaw was solved for radius, camera acceleration, twist and spacecraft position.

I ran a tabledump on the jigsaw updated image for instrument position to see if there were any "nan" elements but there are values for everything.  I did this because of findings based on #4942 even though this case is somewhat different because campt run after initializing with new kernels. Thought it was worth a look anyway.

I also wondered if ale cache size was coming into play at all based on findings in #5023 which leads to https://github.com/DOI-USGS/ale/issues/525.  Again, slightly different circumstances since jigsaw doesn't actually produce any errors, but it made me wonder.  I'm not sure what to check there.  We do have 2019 versions of these data (different network though and solution) that could possibly be compared to if need be.

Possibly similar problem as #5124

**Comment by acpaquette** [comment] 2023-04-08 00:12
@lwellerastro This is likely a somewhat known issue in ALE that we have a fix for. If the `jigsawkernelbased_M110860982LE.cub` you have in your `spiceinit`command above is already spiceinit'd it will run with the IsisLabelIsisSpice driver and will simply attach the data already on the cube back into the cube, rather than running with more new spice data. I put a fix for this into ALE but wasn't able to appropriately apply it to ISIS.

I added flags into ALE that will allow us to turn off all IsisSpice drivers, ensuring that spiceinit puts fresh spice on the cube every time. This flag just needs to be set in ISIS

**Comment by acpaquette** [comment] 2023-04-08 00:15
@lwellerastro Just to confirm this, can you try to run the spiceinit command from above with a fresh lroc cube?

**Comment by lwellerastro** [comment] 2023-04-08 00:16
@acpaquette, it's not already spiced.  The step before copies an ingested-only image to the new filename, then the kernel (based on jigsaw updated image) is applied:

```
cp M110860982LE_ingest.cub jigsawkernelbased_M110860982LE.cub

spiceinit from=jigsawkernelbased_M110860982LE.cub shape=user model=LRO_LOLA_SPole75S_LDEM_30m_mar2014_radius.cub spksmithed=true extra="(M110860982LE_jigsawed_ck.bc,M110860982LE_jigsawed_spk.bsp)"
```
Sorry if that's hard to read!

```
cathist from=M110860982LE_ingest.cub mode=brief
lronac2isis from=M110860982LE.IMG to=M110860982LE_ingest.cub 
```

**Comment by lwellerastro** [comment] 2023-04-08 00:17
```
cathist from=M110860982LE_ingest.cub mode=brief
lronac2isis from=M110860982LE.IMG to=M110860982LE_ingest.cub 
```

**Comment by acpaquette** [comment] 2023-04-08 00:19
No worries, should have read the issue closer!

**Comment by blandoplanet** [comment] 2023-04-10 19:31
This may be related to [#5124](https://github.com/DOI-USGS/ISIS3/issues/5124). The problems seem to be identical although the cause may not be. Better to pursue the problem here (far, far, far higher priority). I'm only cross-linking in case that issue provides clues to address the problem here, or else a fix created here can be applied there.

**Comment by amystamile-usgs** [comment] 2023-05-01 16:53
@lwellerastro This has been taking me some time due to not being able to generating the same results that you were seeing. I found out that this was due to me having a newer version of ale in my environment. It seems that there were a few fixes between version 0.8.6 and 0.8.8 of ale that produced more accurate geometry calculations in comparison to ISIS. The specific changes are discussed in these PRs [#478](https://github.com/DOI-USGS/ale/pull/478), [#479](https://github.com/DOI-USGS/ale/pull/479), [#482](https://github.com/DOI-USGS/ale/pull/482).

Here are the campt differences you provided between `M110860982LE_jigsawed.cub` and `jigsawkernelbased_M110860982LE.cub`. 

<img width="1496" alt="ale0 8 6-campt-diff" src="https://user-images.githubusercontent.com/74275278/235490952-27cb0dc6-7628-4c51-8405-bd1fdae6589b.png">

Then my campt differences with ale version 0.8.8 and `M110860982LE_jigsawed.cub`. 

<img width="1440" alt="ale0 8 8-campt-diff" src="https://user-images.githubusercontent.com/74275278/235491033-f2b96384-a6f9-4d6e-9d95-6687691fec96.png">

Let me know if you believe these geometries are more inline with your expected results.

I will also see if this update in ale also resolves Mike's issue mentioned above.

**Comment by lwellerastro** [comment] 2023-05-01 17:41
Hi @amystamile-usgs, unfortunately I don't the full fix is available yet. The jigsaw updated image and the fresh image spiced using the kernel from jigsaw updated image need to be identical.  It appears the ale version is not completely what's at play here though it seems to have helped some.

The point of the kernel is to apply the jigsaw updates to freshly ingested images and match the jigsaw results without having to bundle images with a network.  I have data from 2021 (framing camera) that confirms the jigsaw data and the kernel applied data have identical information and where they vary (if at all), it's usually past the decimal in the 9th+ location.  It appears in the past when I have performed kernel validation I compared the output of caminfo which includes camstats output, a Geometry group with somewhat more information and a Kernels Group (from the image label) confirming one image was updated by jigsaw and the other had spiceinit run on it and picked up new kernels.  Maybe that is worth doing for the test image, but that fact things aren't close to identical in the output above tells me something else is still not addressed.

I'd be happy to run tests if that's possible, just let me know.

Question - how does a user know what version of ale is being used?

**Comment by amystamile-usgs** [comment] 2023-05-01 18:36
@lwellerastro It is possible that the issue is stemmed back to when the jigsawed images were processed because they too were probably using ale 0.8.6 for these calculations. But i'm not sure.

To check what ale version is being used, run `conda list` and ale should be the first library on the list. You should also be able to manually update ale in your environment by running `conda remove ale` then run `conda install -c conda-forge ale=0.8.8`. 

I will do more digging. I believe when I just removed the option for using ale, the isis results were very close to what ale 0.8.8 was returning but never identical to the original jigged cube. I also confirmed that the kernels from ckwriter and spkwriter were writing correctly. It might be worth looking into the 2021 data you mentioned too. This might be something specific to line scanner images.

**Comment by lwellerastro** [comment] 2023-05-01 19:21
@amystamile-usgs, the images in question were processed under isis7.1.0.  They were ingested into cubes in March and jigsaw with updates was executed on March 31. All very, very recent work. 

Maybe the version of ale needs to be added somewhere on the cube or print file if the have the potential to vary so greatly. More accurate is great, but users need to know something like this has changed and what the ramifications are.  I'm sorry if I missed that information in an announcement.  I'll look more carefully next time.

Once 7.1.0 is activated (I'm working on vm that was built for me but matches astrovm5)
```
 conda list | grep -E 'isis|ale'
# packages in environment at envs/isis7.1.0:
ale                       0.8.7            py39h1a9c180_1    conda-forge
isis                      7.1.0                         0    usgs-astrogeology
```
Which tells what is in use today, but how can tell I what was being used on March 31, if that's relevant? 

This is odd.  When I deactivate, then activate isis7.2.0 I get
```
ale                       0.8.6            py39h1a9c180_0    conda-forge
isis                      7.2.0                   np124_0    usgs-astrogeology
```
and under 8.0.0-RC1
```
ale                       0.8.6            py39h1a9c180_0    conda-forge
isis                      8.0.0_RC1               np124_0    usgs-astrogeology/label/LTS
```
Either way, I don't have a personal isis environment. I use what is in the system and supplied to internal users.  Because of that I can't install anything into the environment. But I sort of think this doesn't matter.  If an image is ingested and updated in a version of isis, using whatever ale version is implemented, then kernels are made under the same versions of things, then images are ingested and spiced with those kernels under the same versions, then they should be identical to the jigsaw file.  These data were processed in a short a period of time and it's hard to believe the version of ale changed in a few weeks, but maybe.

The 2021 images I was referencing were bundled in Dec 2020 and kernels were created in Jan 2021.  The spice runs for the validation make no mention of source (isis vs ale), so I don't think things were implemented at that point. And I was processing under 3.10.2.  But perhaps you are suggesting I apply those kernels to an ingested file today and see if things still match?  I can do that and might have even done so recently.

On top of this, virtually all of the jigsaw updated images for this project were on the bad /scratch hardware and showed corruption so I had to delete the data and I am in the process of recovering everything. It takes a full day plus to stage images for updates and run jigsaw with update=true because the data set is very large.  

I'm not sure what version of ISIS I should be using to do this work and create kernels. I guess I should slightly rephrase that.  Is there a version of isis I should be running jigsaw under and using while updating images?

**Comment by acpaquette** [comment] 2023-05-08 23:29
@lwellerastro Just so there is some traction on this and I am sure you and @amystamile-usgs having been talking about. There is likely an issue in ALE that isn't loading the kernels in the order that ISIS does. ISIS loads all of the extra kernels last, while ALE takes all of the kernels it is given and does a basic sort across the kernels, sorting them in alphabetical order. Which is very blunt compared to ISIS.

This sort is likely not producing the behavior we want to see w.r.t. how kernels are loaded. Currently, we take into account addendum text kernels being loaded last and PCK kernels being loaded first as the addendum kernels often override the PCKs or other text kernels.

Going forward in ALE we need to be a little more delicate with how kernels are loaded. Something to also think about in the new SpiceQL service.

**Comment by lwellerastro** [comment] 2023-05-09 17:34
Thanks for the feedback @acpaquette.  This is maybe starting to make some sense now because I have been testing jigsaw based kernels on other data sets and it's hit or miss whether I see the problem.  There are cases where use of the extra parameter is required, like LROC, ensuring/insisting the the new kernels get applied last.  I'm in the process of testing, but I think Themis IR has a similar problem now.  I'm no kernels expert, but my understanding is order of application can be very important for certain instruments and has something to do with dynamic kernels (??).  At the very least, it seems ALE should be loading user specified kernels in the EXTRA parameter last.

It seems ALE should be following the same loading rules as ISIS (order based on documentation):
```
 As kernels are loaded they override the data in previously loaded kernels. The order in which kernels are loaded is:

    Target Position
    Instrument Position
    Instrument Pointing
    Frame
    Target Attitude Shape
    Instrument
    Instrument Addendum
    Leap Second
    Spacecraft Clock
    Extra

```
There may be more finessing than this.

**Comment by amystamile-usgs** [comment] 2023-05-15 16:22
@lwellerastro I confirmed that Ale is loading the kernels in the correct order. The issue that was happening with is that when specifying a list of extras when spiceiniting, Ale was not including them in total kernels list to load. This was actually fixed in version 0.8.8 of ale and that was why we were seeing better results between 0.8.6 and 0.8.8 versions of ale.

**Comment by lwellerastro** [comment] 2023-05-15 18:00
`I confirmed that Ale is loading the kernels in the correct order. ...This was actually fixed in version 0.8.8 of ale and that was why we were seeing better results between 0.8.6 and 0.8.8 versions of ale.`

I'm glad Ale is loading the kernels in the proper order under the latest version.

If the [attachment](https://github.com/DOI-USGS/ISIS3/issues/5178#issuecomment-1529944342) above is a reflection of 0.8.8 ale applying all kernels specified in the correct order, then I have to disagree that 0.8.8 is that much better.  Some of the differences are quite large.  But maybe it's because the images were processed (ingested, spiced and bundled with updates) via ale 0.8.7 (isis7.1.0) and that version and 0.8.8 have other differences? Being able to compare the projected and mosacked kernel based updated images to a mosaic based on the jigsaw updated images (which I have) would be convincing at the basic geometric level, but the larger differences in illumination, spacecraft and sun groups is really concerning.  It's not just all lat/lon.

Also, why is LRO NAC exclusively picking up ALE drivers and never ISIS drivers.  That doesn't make sense to me.

**Comment by amystamile-usgs** [comment] 2023-05-15 18:59
@lwellerastro I guess I should say 0.8.8 is "better" in terms of the offset you were previously seeing in qview. 
![image](https://github.com/DOI-USGS/ISIS3/assets/74275278/e27aab7b-857b-4486-872c-7db0334dc028)

**Comment by lwellerastro** [comment] 2023-05-15 19:06
yes, I agree, but the other differences are concerning and shouldn't be ignored.
Again, why is LROC picking up ale anyway?

**Comment by amystamile-usgs** [comment] 2023-05-15 20:07
When running spiceinit, it checks for if the driver exists in ale for a particular image being processed. If it can't find a driver, then it will revert to ISIS old spiceinit implementation. That's why you see some use ale and some use isis since some of these drivers are still in the process of being created. We are gonna look more into this issue by running comparisons in Knoten and go from there.

**Comment by lwellerastro** [comment] 2023-05-15 21:48
This is very confusing.  Why are Ale drivers being preferred over isis drivers for any instrument?

Also, ale is not consistent.  I'll have to put another post up, but I just ingested an HRSC image of Phobos under 7.0.0 (ale 0.8.7) and after spiceinit, source=ale.  But when ingested under 8.0.0 (ale 0.8.6), the same raw file ingested and then spiced has source=isis. And they are wildly different when I compare caminfo output of geometry and label information, even though according to the labels they are picking up identical kernels. Clearly, the newer version of isis is using an older version of ale that seems quite different than the newer version available, but why?  It seems the mechanism for tying ale versions to isis versions needs improvement.  And why such vast differences? And not documented anywhere.  

Differences in spice can be very impactful to projects, especially when they are unexpected and when working with projects that are multi-year that have to use semi-current versions of isis to get to bug fixes.  Some of the differences I'm seeing (particularly with the HRSC image I'm looking at today) are quite unexpected. As a user, I don't know what to do or what version of ISIS I should be under.

**Comment by lwellerastro** [comment] 2023-06-28 18:12
I have reprocessed my data under isis8.0.0-RC2/ALE 0.9.1, updated images via jigsaw and created new kernels.  I have verified the kernels now better match the jigsaw updated images when applied to freshly ingested images.  The various fixes and updates to ALE have addressed the problem. Thank you!

**Closed as completed** 2023-07-31 15:47 UTC
Labels: bug
