### ISSUE TITLE
Fresh WSL Install - Test Data Issues

### ISSUE THREAD

**Issue by ghost** [DOI-USGS/ISIS3#3500] opened 2019-11-11 22:58 UTC
Hello - I'm working to get ISIS3 set up on my PC using WSL. I'm fairly new to using ISIS, but I've been able to successfully run it following the usual setup instructions for Mac and Ubuntu in the past with little issue, although following Trent's instructions all seemed well until trying to run the test CTX images to verify my installation.

The program itself seems to run fine, and I can bring in the test CTX data, but when I go to run printf and mroctx2isis I get:

`**I/O ERROR** Unable to open [/home/jpknightly/.conda/envs/isis3/data/base/translations/pdsImage.trn]. foreach: No match.`

From what I can gather, that may mean that it's a directory-related issue but (I think) I've ensured that all the data directories are filed under the same directory, and that all the data is being brought in accordingly. As a sidenote, it was always easier to verify on Mac or Ubuntu by just going into Finder to visually check where things were dropped, but not possible in WSL for understandable reasons. 

So is it almost certainly a directory issue or are there other options that could be returning this error? Possible solutions? 

Worth noting that I'm trying to get ISIS3 running on WSL due to it being on a more capable computer for handling photogrammetric tasks rather than my Mac and Linux machines, otherwise I would just do this from one of them since they're a little more straight-forward to operate.

Thanks

**Comment by jlaura** [comment] 2019-11-12 02:48
@jpknightly Thanks for the post. This looks like a question (?) and not a bug/enhancement that uses the issue template.

I moved the question over to our [discussion forums](https://astrodiscuss.usgs.gov/t/isis3-install-on-wsl-directory-issues/330) for you. I suspect you will get more traction over there. 

If this is a bug, please reply with reproduction steps so that we can address the issue. If not, would you mind closing the issue and we will all see you over on [astrodiscuss.usgs.gov](https://astrodiscuss.usgs.gov/t/isis3-install-on-wsl-directory-issues/330) (same login credentials that you used to sign up for git work over there, so should be a piece of cake!).

**Closed as completed** 2019-11-12 02:58 UTC
