### ISSUE TITLE
Check if documentation is building

### ISSUE THREAD

**Issue by USGSsakins** [DOI-USGS/ISIS3#640] opened 2018-12-10 21:29 UTC
Following testing refactor, documentation errors are being generated in cron:

Offending program:
* buildIsisCmakeAllSys

**Comment by SgStapleton** [comment] 2018-12-11 21:54
Confirmed that documentation is building. It appears that all of the warnings relating to documentation were introduced with merging the testing branch into dev and has to do with missing @author and @internal tags in all the newly introduced files. The files of concern are the hical object headers in mro, the md5 object header in base, and the BundleSettingsTests.cpp in the  new tests/ directory.

**Comment by jessemapel** [comment] 2018-12-11 22:34
@SgStapleton Histiroy on MD5 is Steven Lambright, July 2nd 2010

**Comment by jlaura** [comment] 2018-12-12 14:28
Should we update the 'how-to' documentation to indicate what is needed in terms of documentation, open tickets associated with the files that need to be fixed right now, and then close this?

**Comment by twilson271828** [comment] 2018-12-14 18:49
That documentation already exists [here](https://github.com/USGS-Astrogeology/ISIS3/wiki/ISIS3-Class-Documentation-Requirements-Using-Doxygen-tags)  because the problem has come up before.  Moving it to the 'how-to' sounds like a good idea.

**Comment by SgStapleton** [comment] 2018-12-18 02:20
@twilson271828 Do you think it may be worth it to mention that this includes class declarations within test files...?

**Closed as completed by SgStapleton** 2018-12-18 02:20 UTC
Labels: internal

**Comment by SgStapleton** [comment] 2018-12-18 02:44
@jessemapel Where did you find the history info for MD5? It looks like it was an RSA Data Security open source file...? Are we even technically allowed to list Lambright as an author...?

**Comment by jessemapel** [comment] 2018-12-18 15:30
Lambright is on the version control history as adding the file. I'm not sure how we should tag something like this

**Comment by SgStapleton** [comment] 2018-12-18 16:03
@jlaura Any thoughts?

**Comment by jlaura** [comment] 2018-12-18 16:30
I think we have two options. If we are confident that slambright did author the code then we should add. Otherwise, we could use a generic ASC author.  

In the MD5.h case, it looks like the author is already listed in the header though - Benjamin Groedelbach. (Not sure how to do an umlaut on this keyboard.). Do we add the necessary tags with this author? Alternatively, can we tell the documentation to skip this file.

Of greater concern here - what is the copyright status on this file? It looks like the code is pushed into a usable licensing place, but I am not sure what the license status actually is.
