### ISSUE TITLE
ISIS3 Commands Won't Work on Terminal - X Server Issue

### ISSUE THREAD

**Issue by GavinT94** [DOI-USGS/ISIS3#4659] opened 2021-10-23 02:39 UTC
I followed the installation process using Conda, but when I activate the isis environment and run a command such as qview, I get the following message:

cannot connect to X server...

Do you have an X server running?

If yes then...

  If you are trying to run this program remotely using ssh, then did you enable X11 forwarding?

If the possible causes cited above have been ruled out and this problem persists, then check your X settings or contact your system administrator.

Aborted (core dumped)

I have downloaded Xming and Putty onto my Windows computer, but I am not sure what host name to connect to. Does the USGS ISIS have a host name or IP address I can use to connect to a X Server? Help would really be appreciated because I need ISIS3 to start some research.

**Comment by jlaura** [comment] 2021-10-23 12:58
@GavinT94 Sounds like either you installed isis on a remote machine. [Here](https://cat.pdx.edu/platforms/windows/remote-access/xming/) is a tutorial on using Xming and Putty with X11 forwarding which should get you up and running.

**Comment by GavinT94** [comment] 2021-10-23 13:49
@jlaura I tried to connect to my Linux IP address/host name but I am now getting connection refused or connection timed out errors. Is this related to how my computer firewall is blocking remote connections?

**Comment by jlaura** [comment] 2021-10-23 14:27
Yup - that is related to the other machine and is not an ISIS issue.

**Comment by GavinT94** [comment] 2021-10-23 14:29
That was my fear. Is there a recommended set-up to install ISIS? I have tried Linux in virtualboxes but it gives me similar errors. Is there a way to use isis wthout having to connect to a remote set up? I followed the instructions on the GitHub page but it kept on making a separate remote location.

**Comment by jlaura** [comment] 2021-10-23 14:33
Unfortunately, no. The installation instructions are for linux and OS X. We do not support windows installations. If you are using a virtual box VM, you also need to use X11 forwarding.

**Comment by GavinT94** [comment] 2021-10-23 14:35
I am continuing to troubleshoot X11 forwarding. I have more luck using Mac to install and run ISIS (it seems to me more straightforward and experiences less issues), tempted to use a Mac machine to run the ISIS3 program.

**Comment by rbeyer** [comment] 2021-10-23 15:38
> Unfortunately, [...], you also need to use X11 forwarding.

Well ... only if you need to use the GUIs.  You can certainly install ISIS remotely, and use command-line only interfaces to run ISIS on your remote machine.  This is a common pattern.  For example, since I only have a laptop locally but I have big linux machines remotely, this works for me.  Of course, when I do need to actually visually inspect the images that I'm operating on, I do take advantage of the X11 forwarding to have the remote machine display locally, which is what you're having issues with.

An alternate, less-fun solution, is to install ISIS on a local system, and do the heavy lifting remotely, and then download the (hopefully few?) images to inspect locally as you go along.  If your local system is less capable, but maybe you're not planning on doing a lot of processing, then a local solution could work.

However, if you can work out the X11 forwarding, that would give you the most flexibility.

**Comment by jessemapel** [comment] 2021-10-25 16:10
I'm going to close this as everything is working as intended. Feel free to continue the discussion, though.

If you really want to work on Windows, WSL2 is fairly good these days. Check out Trent's post from a few years back here:

https://astrodiscuss.usgs.gov/t/running-isis-3-7-under-anaconda-in-windows-10-wsl/222

**Closed as completed by jessemapel** 2021-10-25 16:11 UTC
Labels: question, installation

**Comment by AustinSanders** [comment] 2021-10-25 21:33
@GavinT94 I've run into similar "connection refused" problems with X11 forwarding via ```ssh <hostname> -X```.  I was able to use ```ssh <hostname> -Y```, but please be aware that this is somewhat of a more "risky" solution from a security standpoint, as the -Y option treats the remote machine as a trusted client.

Since there a level of security concern associated with the -Y flag, I can't outright recommend that you use it, but I can recommend that you check out [this](https://askubuntu.com/questions/35512/what-is-the-difference-between-ssh-y-trusted-x11-forwarding-and-ssh-x-u) post to make the decision yourself.
