### ISSUE TITLE
ERROR using stereo

### ISSUE THREAD

**Issue by connor-mac-leod** [DOI-USGS/ISIS3#3430] opened 2019-08-25 09:49 UTC
**ISIS version(s) affected**: 3.6.0, 3.5.2
**NASA ASP version(s) affected**: 2.6.2, 2.6.1

**Description**  

(isis3) MacBook-Pro-di-Piero:stereo pierodincecco$  stereo ESP_053962_1985_RED.map.cub ESP_042134_1985_RED.map.cub result/out

Warning: Stereo file: ./stereo.default could not be found. Will use default settings and command line options only.

[ 2019-Aug-24 18:46:40 ] : Stage 0 --> PREPROCESSING 

	--> Setting number of processing threads to: 8

Warning: Stereo file: ./stereo.default could not be found. Will use default settings and command line options only.

Writing log info to: result/out-log-stereo_pprc-08-24-1846-97211.txt

Using session: isis.

Loading camera model: ESP_053962_1985_RED.map.cub 

Using image files:  ESP_053962_1985_RED.map.cub, ESP_042134_1985_RED.map.cub

Using "./stereo.default"

	--> Computing statistics for left

	  left: [ lo:-0.0508093 hi:0.505731 m: 0.135543 s: 0.0667682]

	--> Adjusting hi and lo to -+2 sigmas around mean.

	    left changed: [ lo:0.00200653 hi:0.26908]

	--> Computing statistics for right

	  right: [ lo:0.0718685 hi:0.160575 m: 0.104662 s: 0.0126175]

	--> Adjusting hi and lo to -+2 sigmas around mean.

	    right changed: [ lo:0.0794272 hi:0.129897]

	--> Normalizing globally to: [0.00200653 0.26908]

Loading camera model: ESP_053962_1985_RED.map.cub 

Error: **ERROR** Unable to initialize camera model from group [Instrument].

**ERROR** Failed to convert string [1,79769313486232e+308] to a double.

Stereo step 0: Preprocessing failed

**Comment by connor-mac-leod** [comment] 2019-08-25 09:51
I have contacted the support forum of the NASA ASP, but they answered that this is a bug related to ISIS, not to the NASA ASP.

Piero

**Comment by connor-mac-leod** [comment] 2019-08-25 09:52
The user who mentioned something of the kind said this was encountered on Ubuntu 18 but not on Ubuntu 19. That issue is here: https://github.com/NeoGeographyToolkit/StereoPipeline/issues/275

**Comment by connor-mac-leod** [comment] 2019-08-25 09:53
I'm using MacOS Mojave (10.14.6)

**Comment by oleg-alexandrov** [comment] 2019-08-25 21:33
I understand that this error is from ASP, so on my plate, but it does get thrown from within ISIS. Did anybody ever run into this with ISIS in a different context? It does not help that I can't reproduce it.

**Comment by jlaura** [comment] 2019-08-25 23:42
Can we get a minimal reproducible example that just makes the failing ISIS call? It is not clear what ISIS program is being called. Then we can also try to reproduce.

**Comment by connor-mac-leod** [comment] 2019-08-26 10:06
Hello, 

here is an example, with Ubuntu 19.04, ASP 2.6.1 and ISIS 3.5.2 :


parallels@parallels-Parallels-Virtual-Platform:/media/psf/Home/work1/isis3$ stereo E0201461.map.cub M0100115.map.cub output_prefix/run

    --> Setting number of processing threads to: 2
Warning: Stereo file: ./stereo.default could not be found. Will use default settings and command line options only.
Cannot find the image file: E0201461.map.cub.



None
Traceback (most recent call last):
  File "/media/psf/Home/work1/isis3/StereoPipeline-2.6.1-2018-09-06-x86_64-Linux/libexec/stereo", line 124, in <module>
    settings=run_and_parse_output( "stereo_parse", args, sep, opt.verbose )
  File "/media/psf/Home/work1/isis3/StereoPipeline-2.6.1-2018-09-06-x86_64-Linux/libexec/asp_system_utils.py", line 265, in run_and_parse_output
    raise Exception('Failed executing: ' + " ".join(call))
Exception: Failed executing: /media/psf/Home/work1/isis3/StereoPipeline-2.6.1-2018-09-06-x86_64-Linux/libexec/stereo_parse E0201461.map.cub M0100115.map.cub output_prefix/run --threads 2 --corr-seed-mode 1 --stereo-file ./stereo.default --tif-compress LZW

Piero

**Comment by connor-mac-leod** [comment] 2019-08-26 11:22
Hello,

I made another test. The "stereo" command is working under the following configuration:

MacOS X 10.11.6 El Capitan
ISIS 3.4.12.6662 (2016-03-15)
ASP 2.5.2-2016-02-29-x86_64-OSX
Python v. 2.7.12

Instead, I got the previously indicated error message with the following configurations:

1)
MacOS X 10.14.6 (Mojave)
ISIS 3.6 with ASP 2.6.2
ISIS 3.5.2 with ASP 2.6.1
Python v.2.7.16

2)
Ubuntu 19.04
ISIS 3.5.2 with ASP 2.6.1
Python 2.7.16

I was wondering, may it be a problem related to the python version? With the Python 2.7.12 the the "stereo" works, while so far it doesn't work with the Python 2.7.16.

What configuration are you currently using?

Piero

**Comment by jlaura** [comment] 2019-08-26 13:54
These are all ASP output. What ISIS commend are these failing on? The full ASP stack trace does not look like it is showing this information.

**Comment by connor-mac-leod** [comment] 2019-08-26 14:00
I don't if this problem is related to that of the ASP, but yesterday I couldn't run the "moc2isis" either:

parallels@parallels-Parallels-Virtual-Platform:/media/psf/Home/work1/isis3/StereoPipeline-2.6.1-2018-09-06-x86_64-Linux/examples/MOC$ mocproc from=M0100115.imq to=M0100115.cub Mapping=NO
**ERROR** Running Isis program [moc2isis] failed with return status [4].
**I/O ERROR** Unable to open [/media/psf/Home/work1/isis3/isis/../data/mgs/translations/mocInstrument.trn].

Piero

**Comment by connor-mac-leod** [comment] 2019-08-26 14:02
I want to make another on my macbook pro with Mojave. How can I specifically download ISIS 3.4.12.6662 ?

**Comment by jlaura** [comment] 2019-08-26 14:04
@connor-mac-leod 
Do you have the moc kernels in your data area? 

Also 3.4.12.6626 is > 2 years old. We are currently supporting 3.8.1. Can you upgrade?

**Comment by jessemapel** [comment] 2019-08-26 16:08
@connor-mac-leod The error that ASP is getting from ISIS is coming from the CameraModelFactory. The factory is unable to instantiate the sensor model because there is a bad value somewhere. Can you provide the labels from the cubes?

Also, can you try running the ISIS campt application on them?

Finally, as @jlaura said, do you have the data area downloaded? You may not need to full kernels but you do need the translation files and such.

**Comment by connor-mac-leod** [comment] 2019-08-26 17:05
True, I just downloaded the base and MRO data, so I'm sure kernels were missing. However, since I'm unfortunately in a rush, I resolved the problem by applying the same configuration of the old iMac mid 2010 with the following working configuration:

MacOS X 10.11.6 El Capitan
ISIS 3.4.12.6662 (2016-03-15)
ASP 2.5.2-2016-02-29-x86_64-OSX
Python v. 2.7.12

to my MacBook Pro with Mojave. So, I downgraded the python version of the MacBook Pro from 2.7.16 to 2.7.12. Then, I copy/pasted the "isis" (3.4.12.6662) and "StereoPipeline-2.5.2-2016-02-29-x86_64-OSX" folders from the iMac with El Capitan to my MacBook Pro with Mojave.

So far (I'm still processing, but I didn't get the error), it works perfectly fine for me.

I'll keep you constantly updated.

Piero

**Comment by jessemapel** [comment] 2019-08-26 18:14
@connor-mac-leod This is probably due to using an older version of ISIS. Prior to ISIS3.6, all of the dependencies were manually built and distributed. This means that for Macs, only 10.11 was supported. We had some success getting pre-3.6 version working with the 10.11 SDK, but really if you want to run ISIS on mac 10.12 or newer, you should use Anaconda and ISIS 3.6+.

**Comment by jessemapel** [comment] 2019-09-04 02:49
@connor-mac-leod Did removing de430 in #3433 fix this too?

**Comment by jessemapel** [comment] 2019-09-16 22:19
I'm going to close this. If the issue still exists please re-open

**Closed as completed by jessemapel** 2019-09-16 22:19 UTC

**Comment by oleg-alexandrov** [comment] 2020-11-18 19:35
For the record, this is elucidated in https://github.com/NeoGeographyToolkit/StereoPipeline/issues/275

**Comment by jessemapel** [comment] 2020-11-18 20:02
Wow, locale errors are quite terrible. Thanks for the follow up @oleg-alexandrov

**Comment by oleg-alexandrov** [comment] 2022-07-11 22:41
I put a fix for this in ASP itself. User's locale is overwritten with US English for ASP programs (hey, when reaching for the stars, leave your accents at home). 

Most likely though, this is some bug in ISIS. If it wants a big number, and it creates this: 1,79769313486232e+308, it shows somewhere it uses the decimal separator from user's system, rather than having a hard-coded dot, as you would do with sprintf. I could not trace it beyond the fact that the error is in ShapeModelFactory, which is called by Spice, which is called by Isis::Cube.

**Comment by oleg-alexandrov** [comment] 2022-07-12 04:41
To get to the root of the problem, and given that, as I see, ISIS users ran into converting strings with commas to double in other contexts, one could simply replace the comma with a dot in the string-to-double conversion function here: https://github.com/USGS-Astrogeology/ISIS3/blob/aab0e63088046690e6c031881825596c1c2cc380/isis/src/base/objs/IString/IString.cpp#L149.

**Comment by Toldbo** [comment] 2022-08-30 18:24
Hello
I encounter this error again today in 2022. I have not changed the stereo.default (I don't provide one in the call). I have ISIS=6.0.0. and asp=3.1.0. It works on my other mac. The only other error I see along the way is this when running spiceinit i get a warning: Execution of PAC script at "http://wpad/wpad.dat" failed: The operation couldn’t be completed. (NSURLErrorDomain error -1003.)

please help. 

**ASP CALL**
parallel_stereo /Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008195_11275021648F1F.cub /Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008203_11275022217F1F.cub /Users/toldbo/workArea/imgFolder/corneliaFiles1B/testresult 


Error: **ERROR** Unable to initialize camera model in Camera Factory.
**ERROR** Failed to convert string [1,79769313486232e+308] to a double.
	--> Setting number of processing threads to: 4
Stereo file ./stereo.default could not be found. Will use default settings and command line options only.
num_stereo_pairs,1
Using session: isis
Loading camera model: /Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008195_11275021648F1F.cub 
multiview_command_10001,stereo_parse,--corr-seed-mode,1,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008195_11275021648F1F.cub,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008203_11275022217F1F.cub,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/testresult
in_file1,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008195_11275021648F1F.cub
in_file2,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008203_11275022217F1F.cub
cam_file1,
cam_file2,
input_dem,
extra_argument1,
extra_argument2,
extra_argument3,
stereo_session,isis
stereo_default_filename,./stereo.default
left_image_crop_win,0,0,0,0
out_prefix,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/testresult
left_image_size,1024,1024
right_image_size,1024,1024
trans_left_image,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/testresult-L.tif
trans_right_image,/Users/toldbo/workArea/imgFolder/corneliaFiles1B/testresult-R.tif
trans_left_image_size,0,0
Loading camera model: /Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008195_11275021648F1F.cub 

None
Traceback (most recent call last):
  File "/Users/toldbo/opt/anaconda3/envs/asp/bin/parallel_stereo", line 815, in <module>
    settings = run_and_parse_output("stereo_parse", args, sep, opt.verbose)
  File "/Users/toldbo/opt/anaconda3/envs/asp/libexec/asp_system_utils.py", line 294, in run_and_parse_output
    raise Exception('Failed executing: ' + " ".join(call))
Exception: Failed executing: /Users/toldbo/opt/anaconda3/envs/asp/bin/stereo_parse /Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008195_11275021648F1F.cub /Users/toldbo/workArea/imgFolder/corneliaFiles1B/cubs/FC21B0008203_11275022217F1F.cub /Users/toldbo/workArea/imgFolder/corneliaFiles1B/testresult --corr-seed-mode 1

**Comment by oleg-alexandrov** [comment] 2022-08-30 18:35
You can try the workaround suggested at https://github.com/NeoGeographyToolkit/StereoPipeline/issues/275, which is setting in a shell before starting ASP the values:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

Note that this is no longer necessary in the daily build of ASP, as these are now set for you. That build can be found at the top of  https://github.com/NeoGeographyToolkit/StereoPipeline/releases.

The true root of the problem is in ISIS itself, of course. The "toDouble()" function should replace the comma with a period before parsing it.

**Comment by Toldbo** [comment] 2022-09-08 20:07
Thank you that solved it.

**Comment by yajnab** [comment] 2023-04-03 10:41
Ubuntu 22.04
Error here
None
Traceback (most recent call last):
  File "/home/harshit/Documents/yaj_2005/asp2/libexec/parallel_stereo", line 898, in <module>
    settings = run_and_parse_output("stereo_parse", args, sep, opt.verbose)
  File "/home/harshit/Documents/yaj_2005/asp2/libexec/asp_system_utils.py", line 295, in run_and_parse_output
    raise Exception('Failed executing: ' + " ".join(call))
Exception: Failed executing: /home/harshit/Documents/yaj_2005/asp2/libexec/stereo_parse -t rpc --stereo-algorithm asp_mgm 20221009_051804_32_2499_1B_AnalyticMS.tif 20221009_051806_69_2499_1B_AnalyticMS.tif results/run --corr-seed-mode 1

Anybody please help

**Comment by rbeyer** [comment] 2023-04-03 14:43
@yajnab, it seems that your error doesn't have anything to do with the original parent question in this issue.  This seems to be a question about operation of the Ames Stereo Pipeline (ASP).  Please ask it in the ASP discussion forum: https://groups.google.com/forum/#!forum/ames-stereo-pipeline-support not the ISIS Issue section.  If you do, please also note what command line you issued to result in this error, and the versions of ASP and ISIS that you are using.  Based on the names of directories in your error ouput, I see an "asp2" there, and ASP is currently on version 3.2.0, so perhaps you should update your software.
