### ISSUE TITLE
ISIS C++ Header Boilerplate Disclaimer Needs a Review/Update

### ISSUE THREAD

**Issue by KrisBecker** [DOI-USGS/ISIS3#3741] opened 2020-03-06 22:45 UTC
**Description**

It has been long standing practice for developers to include a USGS/Astro-centric standard disclaimer in the C++ header files of all class object definitions. Since the ISIS repository will be receiving/hosting code from external developers, perhaps its time to review the disclaimer for modifications that may be more appropriate.

```
/**
 * @file
 * $Revision: 1.6 $
 * $Date: 2009/01/07 18:33:38 $
 *
 *   Unless noted otherwise, the portions of Isis written by the USGS are
 *   public domain. See individual third-party library and package descriptions
 *   for intellectual property information, user agreements, and related
 *   information.
 *
 *   Although Isis has been used by the USGS, no warranty, expressed or
 *   implied, is made by the USGS as to the accuracy and functioning of such
 *   software and related material nor shall the fact of distribution
 *   constitute any such warranty, and no responsibility is assumed by the
 *   USGS in connection therewith.
 *
 *   For additional information, launch
 *   $ISISROOT/doc//documents/Disclaimers/Disclaimers.html
 *   in a browser or see the Privacy &amp; Disclaimers page on the Isis website,
 *   http://isis.astrogeology.usgs.gov, and the USGS privacy and disclaimers on
 *   http://www.usgs.gov/privacy.html.
 */
```

Here are some things to consider while thinking about this review:

1. Perhaps this is no longer needed and can be removed altogether.

2. Should code be attributed to individual(s) and/or institution(s) contributing the code? If so, what is the recommended way to do this?

3. Is the USGS committed to ongoing/continuous support of submitted/accepted code indefinitely or are there conditions that developers must acknowledge/agree/commit to?

4. Under what conditions would code be removed from ISIS (e.g., the ISIS/IDL DLM plugin)? What is the process to remove code?

5. How does this situation apply to main applications, i.e., main C++ source files and XML documentation files?

6. How do these decisions affect USGS developers? Anything different needed?

Maybe some of these considerations may appear offtopic but they could be relevant to decisions about the disclaimer. Or not and they may need a separate issue to address.

**Suggested Edit**

None at this time.

Thanks!

**Comment by rbeyer** [comment] 2020-03-10 22:09
> 1. Perhaps this is no longer needed and can be removed altogether.

There should be a standard boilerplate, it should not be this.  The first three lines of the example are clearly a remnant of a previous version control system and should be removed.

The first paragraph is really a statement about the whole library, and doesn't belong in each individual file.

The second paragraph is essentially covered by the top-level license information, and unless you want to reproduce--in full--the license terms in every file, should also be removed.

The third paragraph is great, referring people to other files is good, but the reference to those URLs is a risk for link-rot.

I think the boilerplate should be something short like this that references more detailed files:

```
This is free and unencumbered software released into the public domain.

The authors of ISIS do not claim copyright on the contents of this file.
For more details about the LICENSE terms and the AUTHORS, you will
find files of those names at the top level of this repository.
```

So we already have a LICENSE file.  There is no AUTHORS file, but this could be slowly created as files in the codebase are updated.

> 2. Should code be attributed to individual(s) and/or institution(s) contributing the code? If so, what is the recommended way to do this?

Typically, if this codebase allowed copyright submissions, then individuals and institutions would be named in a set of 'Copyright' lines in each file, and those 'Copyright' lines would need to be updated as people contributed.  However, since all contributions to the ISIS codebase must be released into the public domain, we are not *legally* required to list people in each file.  We could do it anyway, but I think leaving names out of individual files reinforces the public domain nature of the work.  That being said, I think it would be good to encourage people to add their names to the AUTHORS list when they make a commit to the code.

Credits to institutions or acknowledgements for funding or support can also go there.

> 3. Is the USGS committed to ongoing/continuous support of submitted/accepted code indefinitely 

This alone isn't relevant to a boilerplate issue, maybe this needs to be a separate Issue?

> or are there conditions that developers must acknowledge/agree/commit to?

So the only condition (which should be in checkboxes for every PR) is that the code is released to the public domain as it is committed to the repo.
 
> 4. Under what conditions would code be removed from ISIS (e.g., the ISIS/IDL DLM plugin)? What is the process to remove code?

Again, not sure this is relevant to boilerplate, but the process to remove is the same as the process to add: via PR.  If there's something more nuanced here, it should probably be as a separate Issue.

> 5. How does this situation apply to main applications, i.e., main C++ source files and XML documentation files?

By 'this situation' I'm going to assume you mean 'boilerplate text' (if not, please clarify).  So whatever the 'boilerplate' is that we agree to, it should be present in every file that that is reasonably copyrightable.

So yes, it should be in .cpp files and XML documentation files, too.

Minimal configuration files that don't contain significant 'content' probably don't need it (like the top-level environment.yml file).

> 6. How do these decisions affect USGS developers? Anything different needed?

Changing the boilerplate to what I'm suggesting, or anything that we decide upon shouldn't affect the USGS developers at all.  USGS employees, in the course of their duties, can not claim copyright in the works they produce, and so their contributions have always been to the public domain.

**Comment by jlaura** [comment] 2020-03-11 14:23
Disclaimer: I absolutely detest large license blocks at the top of every file. I understand why licenses like GPL strongly suggest including the blocks. This is just a bias I am bringing to this discussion.

Without having done ample due diligence to see what our requirements are:

- We are already licensed using the UnLicense. All the boilerplate that is in the codebase now is rotted.
- I would prefer not to copy the UnLicense into every file.
- [SPDX](https://spdx.org/licenses/) supports the [UnLicensed](https://spdx.org/licenses/Unlicense.html) meaning 
- we can condense all of the text in the source files down to: `// SPDX-License-Identifier: UnLicense`, adopt a standard license used across Public Domain projects that supposedly (IANAL) works in jurisdictions that have no concept of public domain.

Replying to comments:

> Should code be attributed to individual(s) and/or institution(s) contributing the code? If so, what is the recommended way to do this?

We have an authors file and version control. I would like to move away from 'ownership' within the code base to collective ownership of the code base.

> Is the USGS committed to ongoing/continuous support of submitted/accepted code indefinitely or are there conditions that developers must acknowledge/agree/commit to?

I concur with @rbeyer, this has nothing to do with boilerplate license text. If/when this gets posted on Astrodiscuss (it is a question after all), I would strongly suggest presenting some scenarios on how you envision this working. Who is okaying the inclusion of the code? Who is paying for the long-term support? What does LTS even mean? and so on.

> Under what conditions would code be removed from ISIS (e.g., the ISIS/IDL DLM plugin)? What is the process to remove code?

This also has nothing to do with licensing. See above re: AstroDiscuss. This would make a great second question. Alternatively, this could be submitted as an RFC where the author presents their preferred policy.

> How does this situation apply to main applications, i.e., main C++ source files and XML documentation files?

I concur with @rbeyer, please define 'situation'. If this is license text, then everything in the repo is licensed identically (a case to keep any boilerplate as centralized as humanly possible in case of a future change.)

> How do these decisions affect USGS developers? Anything different needed?

@rfergason and I are on that.

**Comment by jlaura** [comment] 2020-04-01 16:47
Looking at the current federal policy, we have identified broadly what policies we need to follow.  

# Proposal:
- Adopt the 18F federal government license (CC0 1.0): https://github.com/18F/open-source-policy/blob/master/LICENSE.md
- Alter the boilerplate in each file to use the SPDX identifier for CC0 1.0: https://spdx.org/licenses/CC0-1.0.html

This is not an API altering change. Do we need to get a RFC open for this or can we get some discussion on here from contributors and make a decision.

**Comment by jessemapel** [comment] 2020-04-01 17:11
Taking the 18F license seems reasonable. Now who wants to write a script to go through the repo and replace all of the boilerplate!

**Comment by rbeyer** [comment] 2020-04-01 17:54
I do not think that an RFC process is needed.  Discussion here should be sufficient.

The 'license file' that is exhibited on the '18F' repo really isn't that great for ISIS, in my opinion (but could be a good model), but I first want to ask why you think you need to move from the 'Unlicense' text to something based on CC0.

**Comment by rfergason** [comment] 2020-04-01 20:58
I agree that discussion here is also likely sufficient and that an RFC is not needed.

**Comment by jlaura** [comment] 2020-04-03 02:57
@rbeyer Simply to get in line with other gov. licenses. The effort is to make the approval process on our side as straightforward as possible.

What are your concerns about CC0 1.0 vs. Unlicense?

@rfergason thanks for aiming me at this as well: https://github.com/usgs/best-practices/blob/master/LICENSE.md

The USGS best practice is also to use CC0 1.0.

**Comment by rbeyer** [comment] 2020-04-04 02:08
No particular concerns, both the Unlicense and CC0 are waivers of copyright.  It is just that CC0 is more general, and applies to any kind of work, whereas the Unlicense is slightly more 'software' oriented.  Unless there were some driving reason, they're equivalent, and I'd stick with the Unlicense.

Ah, that's what I was trying to get to: what 'approval process' are you talking about?

Isn't the brave new world of ISIS a community project that your employees are directed to contribute (their contributions being in the public domain)?  Does your organization require that such external software projects carry a specific license?  That seems odd given the legal nature of your contributions.

Or are you still operating under a conceptual model where the ISIS project is solely a 'work of the United States Government' that you need to seek release authority for from the USGS?  I would argue that it is not.  Once upon a time it was, but no longer.

**Comment by jlaura** [comment] 2020-04-06 14:40
I still need to get this approved through our internal mechanisms. Just like when we are on a paper with external folks, we still have to comply with our internal requirements. 

While we are open sourcing the software and acting as contributors, we are still in this transition of ownership and being required by the organization to abide by the organizational requirements. Honestly, we will always being required to abide by some level of this because we are being directly funded to develop the code base.

It may be possible to get an exception to use the UnLicense, but if the organization is using CC0 1.0 and they are basically equivalent it appears to be significantly easier on the approval side to use the USGS linked CC0 1.0 license. Therefore, I'm advocating for the linked 1.0 with the following text:

```
License
=======

Unless otherwise noted, This project is in the public domain in the United
States because it contains materials that originally came from the United
States Geological Survey, an agency of the United States Department of
Interior. For more information, see the official USGS copyright policy at
https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits

Additionally, we waive copyright and related rights in the work
worldwide through the CC0 1.0 Universal public domain dedication.


CC0 1.0 Universal Summary
-------------------------

This is a human-readable summary of the
[Legal Code (read the full text)][1].


### No Copyright

The person who associated a work with this deed has dedicated the work to
the public domain by waiving all of his or her rights to the work worldwide
under copyright law, including all related and neighboring rights, to the
extent allowed by law.

You can copy, modify, distribute and perform the work, even for commercial
purposes, all without asking permission.


### Other Information

In no way are the patent or trademark rights of any person affected by CC0,
nor are the rights that other persons may have in the work or in how the
work is used, such as publicity or privacy rights.

Unless expressly stated otherwise, the person who associated a work with
this deed makes no warranties about the work, and disclaims liability for
all uses of the work, to the fullest extent permitted by applicable law.
When using or citing the work, you should not imply endorsement by the
author or the affirmer.



[1]: https://creativecommons.org/publicdomain/zero/1.0/legalcode
```

**Comment by rbeyer** [comment] 2020-04-06 17:31
> I still need to get this approved through our internal mechanisms. Just like when we are on a paper with external folks, we still have to comply with our internal requirements.

Sure.  I get that, and it is actually a great example, because what we're talking about with the license and boilerplate on this software project is analogous to the final copyright statement on a published paper.  So let's say you and I are co-authors on a paper.  You have to go through some process internal to the USGS to get them to approve your contribution, and your contribution to the collaboration is provided under the public domain.  I have to go through some process internal to my employer, but my contribution to the collaboration is born with copyrights, as a private citizen.  When the two contributions are mingled, the authors collectively must decide on a rights status.  The author with copyrights could dedicate their contribution to the public domain, but this makes 3rd party publishers nervous, and so they generally treat any paper where even one author could claim copyright as if the author collective could.  Traditional journals request a copyright transfer from those that can claim copyright and publish the derived work as "Copyright the publisher".  Open Access journals, just affirm a CC license, and typically would publish such a paper as "Copyright the authors."

In either case, even though you went through an internal process to approve your contribution as public domain under USGS rules, that only governs your contribution, and the final work can and does have a slightly different copyright situation.

So my general point is that whatever you have to do to satisfy your internal processes really applies at the time of contribution (PR), not to the state of the final project, because in the logical Venn diagram, the final project is outside the USGS circle.

I know that this is different from how things were, but I think it is very important that if you want ISIS to really evolve to be a community project, you may need to adjust a bunch of habits that you and your organization have.

> While we are open sourcing the software and acting as contributors, we are still in this transition of ownership and being required by the organization to abide by the organizational requirements. Honestly, we will always being required to abide by some level of this because we are being directly funded to develop the code base.

Sure, my point is that your "contributions" must abide by these requirements, but the project may not.

> It may be possible to get an exception to use the UnLicense, but if the organization is using CC0 1.0 and they are basically equivalent it appears to be significantly easier on the approval side to use the USGS linked CC0 1.0 license. 

I'm not hard over on the Unlicense.

> Therefore, I'm advocating for the linked 1.0 with the following text:

This is for the top-level 'LICENSE' file, right?  The example text could work as a boilerplate for USGS PRs, but to make it work for the top-level LICENSE file, I'd make these changes:

> ```
> License
> =======
> 
> Unless otherwise noted, This project is in the public domain in the United
> States because it contains materials that originally came from the United
> States Geological Survey, an agency of the United States Department of
> Interior. For more information, see the official USGS copyright policy at
> https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits
> ```
Change the above paragraph to these three:
```
Unless otherwise noted, this project is in the public domain in the United
States.

It contains materials that originally came from the United States Geological
Survey, an agency of the United States Department of Interior.  For more
information on their copyright policies, see 
https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits

It also contains materials from contributors that have waived their copyright
interest to the public domain.
```
> ```
> Additionally, we waive copyright and related rights in the work
> worldwide through the CC0 1.0 Universal public domain dedication.
>  ```

Change "we" in the above to "the authors."

> ```
> CC0 1.0 Universal Summary
> -------------------------
> 
> This is a human-readable summary of the
> [Legal Code (read the full text)][1].
> 
> 
> ### No Copyright
> 
> The person who associated a work with this deed has dedicated the work to
> the public domain by waiving all of his or her rights to the work worldwide
> under copyright law, including all related and neighboring rights, to the
> extent allowed by law.
> ```

Change the sentence above to start:
"The authors have associated their contributions to the ISIS project with this deed, and  have dedicated the work to the public domain by waiving all of their rights to the work ..."

> ```
> You can copy, modify, distribute and perform the work, even for commercial
> purposes, all without asking permission.
> 
> 
> ### Other Information
> 
> In no way are the patent or trademark rights of any person affected by CC0,
> nor are the rights that other persons may have in the work or in how the
> work is used, such as publicity or privacy rights.
> 
> Unless expressly stated otherwise, the person who associated a work with
> this deed makes no warranties about the work, and disclaims liability for
> all uses of the work, to the fullest extent permitted by applicable law.
> When using or citing the work, you should not imply endorsement by the
> author or the affirmer.
> ```

Change the above para to:

"Unless expressly stated otherwise, the authors who have associated the ISIS project with this deed make no warranties about the work, and disclaim liability for all uses of the work, to the fullest extent permitted by applicable law. When using or citing the work, you should not imply endorsement by the authors.

> ```
> [1]: https://creativecommons.org/publicdomain/zero/1.0/legalcode
> ```

Of course, these last two paras are redundant with the CC0 deed, and I think could be omitted.

**Comment by jlaura** [comment] 2020-04-06 18:36
@rbeyer Do you want to put in a PR with those changes? They look good here. The time you spent reviewing and making modifications is appreciated!

We should keep this issue open since the change then needs to propagate to the boilerplate at the top of each file.

**Comment by rbeyer** [comment] 2020-04-07 05:30
So this issue has boilerplate in the title, but so far, we just worked on a new version of the top-level LICENSE file.  What actually should the boilerplate in each file be?

**Comment by jlaura** [comment] 2020-04-07 14:18
I would like to simply see: `/* SPDX-License-Identifier: CC0-1.0 */` as the boilerplate.

**Comment by rbeyer** [comment] 2020-04-07 14:57
I don't think that's enough.  I'd also like to see some minimal statement so if someone landed on  a random file, they have some inkling of what's going on, maybe like this:

```
/** This is free and unencumbered software released into the public domain.

The authors of ISIS do not claim copyright on the contents of this file.
For more details about the LICENSE terms and the AUTHORS, you will
find files of those names at the top level of this repository. **/

/* SPDX-License-Identifier: CC0-1.0 */
```

Or maybe something like this (which is modeled on our PR template):

```
/** This work is free and unencumbered software released into the public domain.
In jurisdictions that recognize copyright laws, the authors of this software
dedicate any and all copyright interest in the software to the public domain. **/

/* SPDX-License-Identifier: CC0-1.0 */
```

Or even:

```
/** This work is free and unencumbered software released into the public domain. **/

/* SPDX-License-Identifier: CC0-1.0 */
```

However, I like the first one, as it directs folks to the top-level files that have more information about the public domain dedication and the authors file.  This latter may help keep the authors themselves from adding author-info to the individual files, and also remind them to add themselves to the AUTHORS file as part of their PR, if they aren't there already.

**Comment by jlaura** [comment] 2020-04-07 20:44
I am good with any of the three. I would lean #1 too if only to get Author info out of the source and into AUTHORS.txt

**Comment by rfergason** [comment] 2020-04-08 13:59
I also lean towards #1 and echo appreciation to @rbeyer for the thorough review and suggestions for improving the text.  Thank you!

**Comment by rbeyer** [comment] 2020-04-08 16:51
Thanks, I have a very strange copyright hobby.  

You know, I don't actually see an AUTHORS.txt file.  Is there one in some other branch or somewhere?  We probably should at least get a minimal version committed if we're going to go with my first option which talks about it.

**Comment by jessemapel** [comment] 2020-04-09 14:56
I don't believe we have one. It shouldn't be hard to make one from the commit history.

**Comment by rbeyer** [comment] 2020-07-08 18:56
I think that with the two merged PRs defined above, this Issue can be closed.

**Closed as completed** 2020-07-08 19:12 UTC
