### ISSUE TITLE
band priority is not optimized in automos

### ISSUE THREAD

**Issue by espeyerer** [DOI-USGS/ISIS3#3711] opened 2020-02-25 16:55 UTC
**ISIS version(s) affected**: 3.x and 4.x

**Description**  
Most users use the default "ontop" or "beneath" when making mosaic products with automos. However, there are some cases when band priority is used (i.e. mosaic regions of images such that the emission angle is minimized in the final map product).  Using this band option, automos must compare the incoming band to a band in the mosaic.  In the current form, this is a slow process and is not optimized.  It is actually quicker to compare images in fx and mosaic the output portions later.  However, this is not ideal for large datasets and would become a large file management task.    

**How to reproduce**  
Compare run times for:
    automos priority=ontop ....
    automos priority=band ...   

**Possible Solution**  
Incorporate optimizations used in other isis functions (i.e. fx) to speed up band comparisons.

**Additional context**  
This issue was discussed with Stuart Sides at the LROC/Diviner team meeting in February 2020.

**Comment by scsides** [comment] 2020-03-03 16:18
There were no optimizations added when the initial feature was added. Suggest profiling a large run and identify places to concentrate on.

**Comment by jlaura** [comment] 2020-03-23 14:08
![](https://github.trello.services/images/mini-trello-icon.png) [band priority is not optimized in automos](https://trello.com/c/mFRqKmv5/85-band-priority-is-not-optimized-in-automos)

**Comment by jlaura** [comment] 2020-09-01 23:25
@victoronline @scsides I missed this in the mission prioritization. Apologies. Is this still an issue that we should add to the mission priority list this sprint?

**Comment by scsides** [comment] 2020-09-03 16:01
Seems reasonable. It is likely unnecessarily slow.

**Comment by jessemapel** [comment] 2020-09-04 16:10
This is still something we should look into.

**Comment by victoronline** [comment] 2020-12-15 18:12
This is still active.

**Comment by AustinSanders** [comment] 2020-12-31 21:39
We weren't able to address the optimization problem this sprint, but we were able to spend some time digging into it.

Based on some profiler runs, it looks like the majority of the time is spent in ProcessMosaic::BandPriorityWithNoTracking, which contains a set of 3 nested for loops.  It looks like Fx uses a BandCalculator to perform its computations, which is where the optimizations are happening.

This issue will likely require a rewrite of the ProcessMosaic::BandPriorityWithNoTracking function to incorporate the cubecalculator.

**Comment by jlaura** [comment] 2021-06-15 12:10
@scsides Was this closed in the last support sprint?

**Comment by victoronline** [comment] 2021-06-18 21:24
Hello All. I don't know if this was waiting for me or not. I believe we were looking at using an alternate resource stream for work on this by Stuart for LROC. As far as LROC is concerned, this option has been discussed by LROC and is a viable option.

**Comment by victoronline** [comment] 2021-08-04 22:37
Any update on this one? Stuart, have you had a chance to look at this one?

**Comment by scsides** [comment] 2021-08-05 18:01
We have a good idea where the problem is. I need to spend a little more time fixing it

________________________________
From: Victor Silva ***@***.***>
Sent: Wednesday, August 4, 2021 3:37 PM
To: USGS-Astrogeology/ISIS3 ***@***.***>
Cc: Sides, Stuart C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [USGS-Astrogeology/ISIS3] band priority is not optimized in automos (#3711)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Any update on this one? Stuart, have you had a chance to look at this one?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-Astrogeology%2FISIS3%2Fissues%2F3711%23issuecomment-893019959&data=04%7C01%7Cssides%40usgs.gov%7C24628ee733844d4bc5ee08d957987995%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637134654860780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NYZhrl4yu%2F9DepkiWJ3uvaWmNPYgE5hjqX%2BDflDnKFE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC25ETIMT7WJFC6T5GE5WHDT3G6KXANCNFSM4K3OFC3A&data=04%7C01%7Cssides%40usgs.gov%7C24628ee733844d4bc5ee08d957987995%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637134654860780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ku4yuGGpIKjbBqlJOit7ch9lbB%2FmuWOxWMXg2h1ujbY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cssides%40usgs.gov%7C24628ee733844d4bc5ee08d957987995%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637134654870735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S0LfzZzAcZtUd0NAQJFmfzPHcwIP3Y20barL4sfhn6I%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cssides%40usgs.gov%7C24628ee733844d4bc5ee08d957987995%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637637134654870735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cW6gqkfc0QBJn0oZL66UMKOBnm9lgkTmJ%2BeBA256NDM%3D&reserved=0>.

**Comment by jessemapel** [comment] 2022-02-11 18:32
Fixed by #4793

**Closed as completed by jessemapel** 2022-02-11 18:32 UTC
Labels: enhancement, Missions
